### PR TITLE
Ensure that any model loaded as a "normalized" joint ordering w.r.t. its default base

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/idyntree/issues/491 . 
WIP because it still needs tests and more documentation, but it can be already tested  @ahoarau .

### CODE REVIEW

**Comment by ahoarau** [comment]
Thanks ! not working yet though..
```
[ERROR] createModelWithNormalizedJointNumbering error :  Link world not found in the input model
[ERROR] URDFDocument :: documentHasBeenParsed : Failed to remove fake links from the model
[ERROR] XMLParser :: parserCallbackEndDocument : Document final callback failed processing
orca::robot::RobotModel::loadModelFromString@174: Robot model 'lwr' (7 dof) successfully loaded
Robot model 'lwr'
  Joints
      Joint 0 joint_1
      Joint 1 joint_0
      Joint 2 joint_2
      Joint 3 joint_6
      Joint 4 joint_3
      Joint 5 joint_5
      Joint 6 joint_4
```

**Comment by traversaro** [comment]
So lucky! You had a model that unveiled an actual bug. Fixed in https://github.com/robotology/idyntree/pull/492/commits/fe5a3d707372ab66b1c1cd6c43684913526c3f7e .

**Comment by ahoarau** [comment]
It's working ! Awesome work Silvio !

**Comment by traversaro** [comment]
Blocked by https://github.com/robotology/idyntree/issues/491#issuecomment-423187338 .

**Comment by ahoarau** [comment]
@traversaro ping on merging ?

**Comment by traversaro** [comment]
> In other words, the models that can be obtained with the new methods of this PR will output serialized vectors related to the indices:
> 
> ```
> [0, ..., nrOfControllableDofs - 1, ..., nrOfControllableDofs + nrOfFixedJoints - 1]
> ```
> 
> Right?

Exactly, but that was the case also before for models loaded with the URDF loader. What this PR adds is that is make sure that the ordering of the non-fixed joints is "normalized" in the sense described in https://github.com/robotology/idyntree/pull/492/files#diff-0adb5bef80354ab9aeb053217960483dR70 , i.e. "parent" joints (w.r.t. to the default base) come before "child" joints. This is rather useless in complex branched tree like models (such as Humanoids robots) were the serialization is typically explicitly specified, but is quite fundamental to respect the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) when loading serial models such as 6 or 7-axis industrial manipulators: the default joint order should be `axis1`, `axis2`, ..., `axis6`. 

> I have a memory though that fixed joints are removed by iDynTree, and links attached to them are lumped to their parent. Only the lumped link frames are kept as additional frame associated to their parent. Can you please remember me the details about this behavior?

URDF fixed joints **are not** removed by default in the iDynTree URDF parser (that is the default behavior of the URDF --> SDF converter in SDFormat/Gazebo), but what is transformed in additional frames are "URDF fake links", that are defined as massless links connected just with a single fixed joint (see https://github.com/robotology/idyntree/blob/c8bf721b771fa4b1e7c3a940632e121060719a19/src/model/include/iDynTree/Model/ModelTransformers.h#L30 and https://github.com/robotology/idyntree/blob/a2fe834d44b9070d93dcc0e9b233f01084e2e835/src/model_io/urdf/src/URDFDocument.cpp#L124). For "URDF fake links" their corresponding fixed joint is indeed eliminated in iDynTree. 
To be more specific, in general "real fixed joint" are not removed in iDynTree, unless a user ask to load a reduced model, and does not include the fixed joints in the list of the desired joints. In that case indeed all non-selected joints (including fixed joints) are lumped, see https://github.com/robotology/idyntree/blob/c8bf721b771fa4b1e7c3a940632e121060719a19/src/model/include/iDynTree/Model/ModelTransformers.h#L54 and https://github.com/robotology/idyntree/blob/114671fb1a012f6214b35b8462d463fea99781fd/src/model_io/urdf/src/ModelLoader.cpp#L139 .

**Comment by diegoferigo** [comment]
>  "parent" joints (w.r.t. to the default base) come before "child" joints

Ok thanks, now I see the Featherstone-like definition.

> URDF fixed joints are not removed by default in the iDynTree URDF parser (that is the default behavior of the URDF --> SDF converter in SDFormat/Gazebo), but what is transformed in additional frames are "URDF fake links", that are defined as massless links connected just with a single fixed joint.
For "URDF fake links" their corresponding fixed joint is indeed eliminated in iDynTree.
To be more specific, in general "real fixed joint" are not removed in iDynTree, unless a user ask to load a reduced model, and does not include the fixed joints in the list of the desired joints. In that case indeed all non-selected joints (including fixed joints) are lumped

Ok now it's clear, thanks for the explanation. I was confused by this case.  For future reference, this is the definition of a fake link:

https://github.com/robotology/idyntree/blob/a2fe834d44b9070d93dcc0e9b233f01084e2e835/src/model_io/urdf/src/URDFDocument.cpp#L215

**Comment by traversaro** [comment]
> Ok now it's clear, thanks for the explanation. I was confused by this case. For future reference, this is the definition of a fake link:
> 
> https://github.com/robotology/idyntree/blob/a2fe834d44b9070d93dcc0e9b233f01084e2e835/src/model_io/urdf/src/URDFDocument.cpp#L215

Actually the definition is in 
https://github.com/robotology/idyntree/blob/c8bf721b771fa4b1e7c3a940632e121060719a19/src/model/src/ModelTransformers.cpp#L35, that code is a duplicated that need to be removed (see https://github.com/robotology/idyntree/issues/556), sorry for the trouble.

**Pull request merged**
