### PR TITLE
Removed unnecessary warning messages

### PR DESCRIPTION
**Pull request by gabrielenava**
Following https://github.com/robotology/idyntree/issues/408, I removed two unnecessary warning messages.

I changed the condition of the `if` statement to avoid to have empty `else` statements in the logic. I compiled it on Ubuntu 18.04 and tested and it seems ok to me.

I targeted `devel` branch for the PR. If there is any `changelog` to update, I will update it.

### CODE REVIEW

**Comment by gabrielenava** [comment]
cc @nunoguedelha @traversaro @S-Dafarra @CarlottaSartore

**Comment by traversaro** [comment]
Thanks @gabrielenava , please update the CHANGELOG in https://github.com/gabrielenava/idyntree/blob/removedUnnecessaryWarnings/CHANGELOG.md under Unreleased Major .

**Comment by gabrielenava** [comment]
[Changelog](https://github.com/gabrielenava/idyntree/blob/removedUnnecessaryWarnings/CHANGELOG.md) updated under `removed` list.

**Comment by traversaro** [comment]
Thanks @gabrielenava !

**Pull request merged**
