### PR TITLE
GitHub Actions: Update to recent version of vcpkg and enable assimp compilation on Windows

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
Indeed, Assimp on Windows is not working correctly, and it is failing with this error: 
~~~
2020-10-26T17:20:34.5407950Z   idyntree-high-level.vcxproj -> D:\a\idyntree\idyntree\build\lib\Release\idyntree-high-level.lib
2020-10-26T17:20:34.6468360Z   Building Custom Rule D:/a/idyntree/idyntree/src/solid-shapes/CMakeLists.txt
2020-10-26T17:20:34.7734148Z   InertialParametersSolidShapesHelpers.cpp
2020-10-26T17:20:36.3075101Z D:\a\idyntree\idyntree\src\core\include\iDynTree/Core/EigenHelpers.h(275,14): warning C4244: 'argument': conversion from 'const ptrdiff_t' to 'const unsigned int', possible loss of data [D:\a\idyntree\idyntree\build\src\solid-shapes\idyntree-solid-shapes.vcxproj]
2020-10-26T17:20:36.4634023Z D:\a\idyntree\idyntree\src\solid-shapes\src\InertialParametersSolidShapesHelpers.cpp(22,10): fatal error C1083: Cannot open include file: 'assimp/Importer.hpp': No such file or directory [D:\a\idyntree\idyntree\build\src\solid-shapes\idyntree-solid-shapes.vcxproj]
2020-10-26T17:20:36.6192975Z   Building Custom Rule D:/a/idyntree/idyntree/src/core/tests/CMakeLists.txt
2020-10-26T17:20:36.7240108Z   DirectionUnitTest.cpp
2020-10-26T17:20:37.1728801Z D:\a\idyntree\idyntree\src\core\include\iDynTree/Core/TestUtils.h(232,30): warning C4566: character represented by universal-character-name '\u2714' cannot be represented in the current code page (1252) [D:\a\idyntree\idyntree\build\src\core\tests\DirectionUnitTest.vcxproj]
2020-10-26T17:20:37.1731752Z D:\a\idyntree\idyntree\src\core\include\iDynTree/Core/TestUtils.h(242,34): warning C4566: character represented by universal-character-name '\u2714' cannot be represented in the current code page (1252) [D:\a\idyntree\idyntree\build\src\core\tests\DirectionUnitTest.vcxproj]
2020-10-26T17:20:37.8824813Z   DirectionUnitTest.vcxproj -> D:\a\idyntree\idyntree\build\bin\Release\DirectionUnitTest.exe
2020-10-26T17:20:38.7079705Z   Building Custom Rule D:/a/idyntree/idyntree/src/tests/integration/CMakeLists.txt
~~~

**Comment by traversaro** [comment]
This is probably related with your problem @AlbertoRemusIIT , I'll look into it.

**Comment by AlbertoRemusIIT** [comment]
> This is probably related with your problem @AlbertoRemusIIT , I'll look into it.

Yes `idyntree-solid-shapes` was the problematic project in the local VS solution

**Comment by traversaro** [comment]
The problem is due to https://github.com/microsoft/vcpkg/issues/14255 . Basically `assimp_VERSION`  variable in https://github.com/robotology/idyntree/blob/9d3042f77eb76d08084fa70bf5ff868a19202683/src/solid-shapes/CMakeLists.txt#L22 is empty, and then the wrong if clause is taken. As a workaround, I think it is safe to just assume that on WIN32 we can safely use the `assimp::assimp`  imported target.

**Comment by traversaro** [comment]
Compilation with assimp from the latest vcpkg is now working fine.

**Review by AlbertoRemusIIT — APPROVED** [review]

**Comment by traversaro** [comment]
The test that is failing on Windows is: 
~~~
100/100 Test #100: memcheck_IntegrationTestInertialParametersSolidShapesHelpers ...***Failed    0.07 sec
Error:   :: BBFromExternalShape : Impossible to load mesh cube.stl using the Assimp library.
D:\a\idyntree\idyntree\src\tests\integration\InertialParametersSolidShapesHelpersIntegrationTest.cpp:52 : assertTrue failure


99% tests passed, 1 tests failed out of 100

Total Test time (real) =   6.84 sec

The following tests FAILED:
	100 - memcheck_IntegrationTestInertialParametersSolidShapesHelpers (Failed)
Errors while running CTest
Error: Process completed with exit code 8.
~~~
that is exactly what was failing in https://github.com/robotology/idyntree/issues/663 . What is quite strange is that in Windows there is no valgrind, so the test `memcheck_IntegrationTestInertialParametersSolidShapesHelpers`  should be exactly the same of `IntegrationTestInertialParametersSolidShapesHelpers`.

**Pull request merged**
