### PR TITLE
[Inverse Kinematics] Add CoM target

### PR DESCRIPTION
**Pull request by S-Dafarra**
I still need to modify the unit test for debugging this insertion.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Tests seems passing.

**Comment by traversaro** [comment]
@S-Dafarra Travis is highlighting memory problems. Install `valgrind` and `valkyrie` and enable the `IDYNTREE_RUN_VALGRIND_TESTS` option to run the valgrind-based tests on yor local machine.

**Comment by S-Dafarra** [comment]
@traversaro it took nearly 10 seconds, but the ``memcheck_UnitTestInverseKinematics`` passed with no problems.

**Comment by traversaro** [comment]
Mh, it seems to fail on travis for some reason at this line: 
https://github.com/robotology/idyntree/pull/285/files#diff-955ad995d9a7c401e7404ad8dac5e534R312 . 
You can increase the ipopt verbosity in the tests to see what's going wrong.

**Comment by traversaro** [comment]
Hi @S-Dafarra , when you will check this branch can you also check the readability comments provided by @codacy-bot ?

**Comment by S-Dafarra** [comment]
Hi @traversaro , I'm able to see only two issue highlighted by the codacy bot, related to the test (a trailing space, and a space after a comma). Are just those to be fixed?
Secondly it seems that for some reason, ``IPOPT`` is taking forever to find a solution when compiling in ``Debug``, when the CoM target is treated as a constraints and only when running the ``memcheck``. The strange thing is that, when running the very same test without the ``memcheck``, ``IPOPT`` finds a solution for this problem quite rapidly, while hanging on the other case (the target is actually a target).

**Comment by traversaro** [comment]
Exactly!

**Pull request merged**
