### PR TITLE
Several improvements in the swig python bindings

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
Thanks to this PR it is possible to access the elements of `LinkPositions`, `LinkVelArray`, and `LinkAccArray`. Without the PR the elements are inaccessible

### CODE REVIEW

**Comment by traversaro** [comment]
Cool, can you update the CHANGELOG?

**Review by traversaro — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
> Cool, can you update the CHANGELOG?

Unreleased major o unreleased?

**Review by diegoferigo — APPROVED** [review]
looks good!

**Comment by traversaro** [comment]
> > Cool, can you update the CHANGELOG?
> 
> Unreleased major o unreleased? 

Unreleased major

**Comment by traversaro** [comment]
There was a macOS failure:
~~~
...........................................................................E............
======================================================================
ERROR: test_exporter (test_idyntree_modelio_urdf.IDynTreeModelIoUrdfTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/idyntree/idyntree/bindings/pybind11/tests/test_idyntree_modelio_urdf.py", line 28, in test_exporter
    self.assertTrue(exporter.export_model_to_string())
ValueError: Failed to export model.
~~~

That seems strange to be a network flake.

**Comment by GiulioRomualdi** [comment]
I update the changelog 😄

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
