### PR TITLE
Avoid to compute the pseudoinverse to evaluate the external wrenches

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
According to https://eigen.tuxfamily.org/dox/group__LeastSquares.html this should be more efficient

cc @traversaro @S-Dafarra

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
I just realized that in most cases we can also avoid the Qr decomposition, as in the submodels has only one full wrench as unknown, in the equation Ax = b the A is just an adjoint matrix for which the inverse is trivial.

**Comment by GiulioRomualdi** [comment]
I would like to present you some results. I used `perf` to profile the new implementation with respect to the old one (the one with `pinv`)
The command I used is `sudo perf record --call-graph dwarf -p <PID> -- sleep 3` then I analyzed the data with [`hotspot`](https://github.com/KDAB/hotspot)

The following figures shows the result in case of `pinv` (the old method) and the `qr` decomposition (what the PR is proposing)
|  pinv    | QR decomposition   | 
|:---:|:---:|
| Screenshot from 2022-08-29 11-37-48 | Screenshot from 2022-08-29 11-37-37 |

Accordingly to the results the approach I proposed is 2 times faster than the original one.

**Comment by traversaro** [comment]
Great, let's merge then. Given that the base branch of the PR for some reason is quite old, can I rebase on top of the latest master to run the CI?

**Comment by GiulioRomualdi** [comment]
> Great, let's merge then. Given that the base branch of the PR for some reason is quite old, can I rebase on top of the latest master to run the CI?

sure!

**Comment by GiulioRomualdi** [comment]
cc @gabrielenava

**Comment by DanielePucci** [comment]
@gabrielenava we might consider to re-install the iDyntree for the iRonCub

**Pull request merged**
