### PR TITLE
add exisiting python tests to CMakeFile

### PR DESCRIPTION
**Pull request by kjyv**

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks! There seem to be problems in Travis tests. Perhaps we should pass the location of the python binding and compiled libraries to python through CMake, to avoid hardcoding any assumption on the location of the build directory, similar to what we do for matlab in https://github.com/robotology/idyntree/blob/master/bindings/matlab/tests/CMakeLists.txt#L10 or octave in https://github.com/robotology/idyntree/blob/master/bindings/octave/tests/CMakeLists.txt#L15 .

**Comment by kjyv** [comment]
Yeah, it seems a bit cleaner that way. Which path to set though? The tests are copied to CMAKE_CURRENT_BINARY_DIR but then for matlab, e.g. `addpath('${CMAKE_CURRENT_SOURCE_DIR}/../../matlab/tests');` is called. 
For python tests, it should be something like this I guess:
`set_tests_properties(PythonGeometryTests, PROPERTIES ENVIRONMENT "PYTHONPATH=${PYTHONPATH}:${CMAKE_CURRENT_BINARY_DIR}/../:${CMAKE_CURRENT_BINARY_DIR}/../../../lib/python/")`
 It's maybe also easier to just run pytest *.py on the directory instead of adding the tests separately.

**Comment by traversaro** [comment]
I am afraid that `PYTHONPATH=${PYTHONPATH}` will not work as an argument of the [`ENVIRONMENT`](https://cmake.org/cmake/help/v3.7/prop_test/ENVIRONMENT.html) property of `set_tests_properties`. However it should be sufficient to pass as ENVIRONMENT `PYTHONPATH=$<TARGET_FILE_DIR:iDynTree_python>` , using generator expressions ( https://cmake.org/cmake/help/v3.7/manual/cmake-generator-expressions.7.html ) on the target `iDynTree_python`.

**Comment by traversaro** [comment]
Hi @kjyv , I guess you stopped using iDynTree long ago. Anyhow, if anyone is still interesting in merging this PR, I opened a related issue in https://github.com/robotology/idyntree/issues/610 , so feel free to re-open it.

**Pull request closed without merging**
