### PR TITLE
Adding functionalities for Berdy

### LINKED ISSUE #205: Function for selecting sensors loaded from URDF
Consider the following use case: in your URDF model you have a list of sensors that you load by using `ModelLoader` but you want  to use only some of these sensors in the computation.  Actually it doesn't exist a function that allows you to select the sensors. It can be useful to add it.

### PR DESCRIPTION
**Pull request by francesco-romano**
Related issues:
Fix https://github.com/robotology/idyntree/issues/204
Fix #205 

Still missing:

- [x] update `loadReducedModel*` taking into account the list of sensors
- [x] provide dynamic variables ordering (as we provide sensors ordering)

cc @traversaro @claudia-lat

### CODE REVIEW

**Comment by francesco-romano** [comment]
Even if some stuff is missing, I think @claudia-lat can start working with this...

**Comment by francesco-romano** [comment]
First point depends on some "big" change in iDynTree. 
We thus postpone its implementation in the future.

Working on point 2.

**Comment by francesco-romano** [comment]
Ok.
@traversaro  I should have fixed the indices (to correctly handle the traversal).

If it is ok we can merge.

**Comment by traversaro** [comment]
I think there is some valid (in C++98) problem with `typename` placement catched by the VS2013 AppVeyor build. I will check it tomorrow with the Windows VM.

**Comment by francesco-romano** [comment]
@traversaro should be fixed now.
Let's wait for CI

**Pull request merged**
