### PR TITLE
Add the possibility to pass the zmq url to the meshcat visualizer

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This is required to use meshcat-visualizer in colab

@traversaro

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@GiulioRomualdi can I merge or you want to wait?

**Comment by GiulioRomualdi** [comment]
Yes you can merge it since I'm using the very same code in this notebook on colab

https://colab.research.google.com/drive/1qdM6SEZPCUmUQL174jXsRd96RiMxX4ED?usp=sharing&authuser=1#scrollTo=TnHm5vRczzEr

I noticed that `viz.jupyter_cell()` does not show the content of meshcat in colab but I think it's a known issue https://github.com/rdeits/meshcat-python/pull/74

**Comment by traversaro** [comment]
> I noticed that `viz.jupyter_cell()` does not show the content of meshcat in colab but I think it's a known issue [rdeits/meshcat-python#74](https://github.com/rdeits/meshcat-python/pull/74)

Other related issue: https://github.com/RobotLocomotion/drake/issues/12645 .

**Comment by jcarpent** [comment]
@traversaro Thanks for your quick answer in duburcqa/jiminy#403.
Did you manage to display within a Jupyther cell?

**Comment by traversaro** [comment]
> @traversaro Thanks for your quick answer in duburcqa/jiminy#403.
> Did you manage to display within a Jupyther cell?
> 

If I remember correctly, no, just in a separate tab. I don't remember what was the blocking aspect there, but I wonder if removing the zmq intermediate step (as Meshcat for Julia) and implementing directly the websocket server could help. In Drake they are doing something similar by porting the Meshcat bits to C++, I was wondering if it could make sense to port those code in a standalone drake-indepent meshcat-cpp library.

**Comment by jcarpent** [comment]
@traversaro I do agree on the fact that it would be interesting to have an independent package for C++. It would be very useful for everybody ;).

**Comment by jcarpent** [comment]
> I don't remember what was the blocking aspect there, but I wonder if removing the zmq intermediate step (as Meshcat for Julia)

Could you provide more info on how it works on Julia?

**Comment by traversaro** [comment]
> > I don't remember what was the blocking aspect there, but I wonder if removing the zmq intermediate step (as Meshcat for Julia)
> 
> Could you provide more info on how it works on Julia?

I am temporary on my phone, but in the meanwhile you may find some pointers in https://github.com/traversaro/not-working-meshcat-cpp/issues/1 .

**Comment by traversaro** [comment]
> > I don't remember what was the blocking aspect there, but I wonder if removing the zmq intermediate step (as Meshcat for Julia)
> 
> Could you provide more info on how it works on Julia?

I am temporary on my phone, but in the meanwhile you may find some pointers in https://github.com/traversaro/not-working-meshcat-cpp/issues/1 .

**Pull request merged**
