### PR TITLE
Remove  appveyor and Travis CI files

### PR DESCRIPTION
**Pull request by traversaro**
All the CI is now performed via GitHub Actions.

### CODE REVIEW

**Comment by traversaro** [comment]
> I think [CONTRIBUTING](https://github.com/robotology/idyntree/blob/master/CONTRIBUTING.md#continuous-integration) documentation should be changed as well

Thanks for noticing, I added commits https://github.com/robotology/idyntree/pull/609/commits/7911c6be167c91695a07026d86c7a139416ab382 and https://github.com/robotology/idyntree/pull/609/commits/4d454a2b0ec84ccdca2b5192a7ddac085d994dbd to address  this.

**Comment by lrapetti** [comment]
I think also scripts in https://github.com/robotology/idyntree/tree/master/.ci can now be removed right?

**Comment by traversaro** [comment]
> I think also scripts in https://github.com/robotology/idyntree/tree/master/.ci can now be removed right?

Good catch!

**Comment by traversaro** [comment]
> > I think also scripts in https://github.com/robotology/idyntree/tree/master/.ci can now be removed right?
> 
> Good catch!

Done in the last three commits.

**Pull request merged**
