### PR TITLE
Feature/29/add sem checks to spatial vectors

### PR DESCRIPTION
**Pull request by nunoguedelha**
Semantics checks completed for all motion and force 3D and 6D vectors. Some improvements to be done on semantics of force vectors, after further theoretical analysis on Forces, Torques and Wrenches semantics.
Merge on latest master branch to be done shortly after this commit.

### CODE REVIEW

**Comment by traversaro** [comment]
Ok, a fixed a bug in SpatialInertiaRaw::operator* , now all tests are passing, beside the one of the bindings. This because the CRTP templates are not correctly wrapper by swig. 
The main thing to fix before merging are : 
  * Properly wrap the CRTP templates in Swig, as documented in http://swig.10945.n7.nabble.com/Does-SWIG-support-quot-template-of-current-class-quot-inheritance-td12158.html . To get an idea, look how we wrap Vector3/Vector6 . 
  * implement toString() [but this is low priority]

**Comment by nunoguedelha** [comment]
@traversaro , actually I hadn't included the headers which defined template classes in order to avoid binding issues, and also because I didn't want these classes to be part of the bindings interface. I'm mentioning the following headers and respective classes :
- GeomVector3.h
- ForceVector3.h
- MotionVector3.h
- SpatialVector.h

Do you have issues with the wrap of CRTP templates in Swig even if not including `GeomVector3.h` in `iDynTree.i`?
I'm reading your merge and fixes changes ...

**Comment by traversaro** [comment]
The problem is that for example we don't provide  bindings for the template `SpatialVector<SpatialMotionVector, LinearMotionVector3, AngularMotionVector3>` that is defining (for example) the method `toString` for the class Twist, from which class will Twist inherit the `toString` method? If you check, now string is correctly wrapper, but with no useful method because they are all defined in `SpatialVector<SpatialMotionVector, LinearMotionVector3, AngularMotionVector3>` , that is not wrapped.

**Comment by nunoguedelha** [comment]
@traversaro , I've pushed the last updates for having all tests PASS. I'll submit the improvements we discussed in a new branch, along with a full description.

**Comment by traversaro** [comment]
I did some modifications: 
  * removed a typename from the typedef because it was giving a warning ( https://github.com/robotology/idyntree/commit/c8f4f333e9fd5cc5933ba113ddd7984bb3a04319 ). 
  * added fromMatlab/toMatlab in SpatialVector (changed idea... in the end it was not so difficult) ( 8aadce972ab5b7c34999f5bab141b0807004b44c )
  * added the missing .m files in the repo ( https://github.com/robotology/idyntree/commit/99288c6cbc61d7bd904b2e1fd61d44267568e884 )

Non blocking issues that can be resolved after merging the PR : 
* GeomVector3 expose the Eigen headers in an iDynTree header, creating a depedency on the Eigen headers if a user wants to use iDynTree... I would prefer to avoid that, I think it can be easily done by moving the computations to a non-templated class. 
 * I think some traits class (the one not used as a base class of a public class) can be instantiated in SWIG without a name , to avoid polluting too much the generated wrapper.

**Comment by nunoguedelha** [comment]
Thanks @traversaro !
  * Regarding the `typename` keyword used with `typedef`, I usually add this because at the first compilation pass, the compiler considers any template parameter as a value, at least within a `typedef` statement. Probably here it is not mandatory because the class `MotionForce_traits` is **fully** instanciated in the included header "PrivateMotionForceVectorAssociations.h". I'm not sure about the reason...
  * If I understood well, `toMatlab()` and `fromMatlab()` for `SpatialVector` are using the operators `()` added in (https://github.com/robotology/idyntree/commit/4d1a419b6ae3dacbd407f312a48eb20d9e823031).
  * About some of the missing .m files you mentioned, and your last comment about the traits class, I fully agree, as we had discussed, I had only left these names for checking the bindings generation. I'll have to update the macro in `iDynTree.i`... 
  * regarding `GeomVector3.h` and Eigen headers: if we move the computations away from this class we loose the advantage of communalising them. we'll see...

**Comment by nunoguedelha** [comment]
I moved the macro `TEMPLATE_WRAP_MOTION_FORCE` to another interface file "./macrosForTemplates.i" to cleanup "iDynTree.i".
I did some small changes in the macro for :
  * removing unuseful binding files in .../+iDynTree/ folder, like "add.m" (inner macro `#define`'s side effect)
  * adding the capability to instantiate unnamed templates (all the traits class templates). As expected, all the respective unuseful bindings files were removed.

**Comment by traversaro** [comment]
I think we can merge it now... if other issue arise we can fix them from master.

**Pull request merged**
