### PR TITLE
Added some SFINAE checks in Span.

### PR DESCRIPTION
**Pull request by S-Dafarra**

### CODE REVIEW

**Comment by S-Dafarra** [comment]
It seems that bindings are not compiling.

**Comment by traversaro** [comment]
We can just add the `make_span`  definition inside the `#ifndef SWIG`  blocks, as in any case a template function with no implementation is not used at all in the bindings.

**Comment by S-Dafarra** [comment]
> We can just add the `make_span` definition inside the `#ifndef SWIG` blocks, as in any case a template function with no implementation is not used at all in the bindings.

I am not sure I understood. So there will be no ``make_span`` in the bindings. Before it was there I guess, does it make any problem?

**Comment by traversaro** [comment]
> 
> 
> > We can just add the `make_span` definition inside the `#ifndef SWIG` blocks, as in any case a template function with no implementation is not used at all in the bindings.
> 
> I am not sure I understood. So there will be no `make_span` in the bindings. Before it was there I guess, does it make any problem?

My point was that it was not there even before, as there was no explicit instantiation of `make_span`  for a given container, so we are not removing anything.

**Review by traversaro — APPROVED** [review]

**Pull request merged**
