### PR TITLE
Add the possibility to extract submatrix with MatrixView

### LINKED ISSUE #797: Unable to use matrix view with Eigen::Ref and Eigen::Map
If I try to compile the these lines 
```cpp
     iDynTree::MatrixDynSize a;
     m_kinDyn->getFrameFreeFloatingJacobian(m_frameIndex,
                                            iDynTree::toEigen(a));
```
the following error is thrown by the compiler
```
/home/gromualdi/robot-code/robotology-superbuild/build/install/include/iDynTree/KinDynComputations.h:697:10: note:   no known conversion for argument 2 from ‘Eigen::Map<Eigen::Matrix<double, -1, -1, 1> >’ to ‘iDynTree::MatrixView<double>’
```

Something similar happens if I do

```cpp
     m_kinDyn->getFrameFreeFloatingJacobian(m_frameIndex,
                                            this->subA(m_robotAccelerationVariable));

```

where the function `subA` is
```cpp
Eigen::Ref<Eigen::MatrixXd> subA(const VariablesHandler::VariableDescription& description)
{
    return m_A.block(0, description.offset, 6, description.size);
}
```

This is the error
```
bool iDynTree::KinDynComputations::getFrameFreeFloatingJacobian(iDynTree::FrameIndex, iDynTree::MatrixView<double>)
     bool getFrameFreeFloatingJacobian(const FrameIndex frameIndex,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gromualdi/robot-code/robotology-superbuild/build/install/include/iDynTree/KinDynComputations.h:697:10: note:   no known conversion for argument 2 from ‘Eigen::Ref<Eigen::Matrix<double, -1, -1> >’ to ‘iDynTree::MatrixView<double>’
```

Actually supporting the eigen::map is not really important since matrixview can be seen as a map, so we can wrap directly a non-idyntree object using the matrixview. On the other hand, adding the support to `eigen::ref` it would be really nice since it may happen that the input of a function is an `Eigen::Ref` object. 
I think that the problem can be split into these subtasks:
1. understand why the eigen::ref doesn't work out of the box.
2. implement a `SubMatrixView`. This can be used to extract a block from a `MatrixView` (this is actually what I need) 

cc @traversaro and @S-Dafarra

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
With this PR it is possible to extract a submatrix from a MatrixView and it should partially fix #797.

I also update the test with the new feature

cc @traversaro @S-Dafarra

### CODE REVIEW

**Review by traversaro — APPROVED** [review]
Thanks @GiulioRomualdi !

**Comment by traversaro** [comment]
@S-Dafarra I guess this will create conflicts with https://github.com/robotology/idyntree/pull/798 . Can I merge it, and then we will handle the conflicts in https://github.com/robotology/idyntree/pull/798  ?

**Comment by S-Dafarra** [comment]
> @S-Dafarra I guess this will create conflicts with #798 . Can I merge it, and then we will handle the conflicts in #798 ?

Yes, no problems

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
@traversaro self-remainder: this PR changed the ABI , so next release should be iDynTree 3.0 to respect semver for ABI.

**Pull request merged**
