### PR TITLE
Refactor CMake project for Matlab bindings

### PR DESCRIPTION
**Pull request by diegoferigo**
Taking inspiration from https://github.com/robotology/yarp-matlab-bindings/pull/35, this PR refactors the CMake project of the Matlab bindings, fixing https://github.com/robotology/idyntree/issues/743.

cc @gabrielenava @CarlottaSartore if you can try this branch on your setup it would be great

### CODE REVIEW

**Comment by traversaro** [comment]
Thanks @diegoferigo ! Did you tried to regenerate the bindings with this modifications? If you did not, I can try to do it myself. Asking as that part is not currently covered by CI.

**Comment by traversaro** [comment]
@Giulero did you tested this PR? It is working as expected?

**Comment by Giulero** [comment]
I don't have the errore described in https://github.com/robotology/idyntree/issues/743.
I get this one instead:
```
[ 99%] Swig compile ../iDynTree.i for matlab
:3: Error: Unable to find 'matlab.swg'
/home/giuseppe/robotology-superbuild/robotology/iDynTree/bindings/iDynTree.i:5: Error: Unable to find 'std_string.i'
/home/giuseppe/robotology-superbuild/robotology/iDynTree/bindings/iDynTree.i:6: Error: Unable to find 'std_vector.i'
bindings/matlab/CMakeFiles/iDynTreeMEX_swig_compilation.dir/build.make:88: recipe for target 'bindings/matlab/CMakeFiles/iDynTreeMEX.dir/iDynTreeMATLAB.stamp' failed
make[2]: *** [bindings/matlab/CMakeFiles/iDynTreeMEX.dir/iDynTreeMATLAB.stamp] Error 1
make[2]: *** Deleting file 'bindings/matlab/CMakeFiles/iDynTreeMEX.dir/iDynTreeMATLAB.stamp'
CMakeFiles/Makefile2:1351: recipe for target 'bindings/matlab/CMakeFiles/iDynTreeMEX_swig_compilation.dir/all' failed
make[1]: *** [bindings/matlab/CMakeFiles/iDynTreeMEX_swig_compilation.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by diegoferigo** [comment]
> Did you tried to regenerate the bindings with this modifications?

Yes I did, it works in my setup with Matlab 2020a. The diff of the bindings is something similar, I don't think is that relevant. Let me know you want me to push the new autogenerated file anyway.

Screenshot_20201009_184908

**Comment by traversaro** [comment]
> > Did you tried to regenerate the bindings with this modifications?
> 
> Yes I did, it works in my setup with Matlab 2020a. The diff of the bindings is something similar, I don't think is that relevant. Let me know you want me to push the new autogenerated file anyway.

No, I wanted just to make sure that the CMake was working in that case.

**Comment by traversaro** [comment]
>  I get this one instead (I was generating the bindings):

That message is strange, you get it also when using the `devel` branch? Are you using SWIG from https://github.com/robotology-dependencies/swig ?

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
In any case, as https://github.com/robotology/idyntree/issues/743 is fixed by this PR, I think it make sense to merge it. We an investigate the @Giulero problem also after the merge.

**Comment by Giulero** [comment]
> That message is strange, you get it also when using the devel branch? Are you using SWIG from https://github.com/robotology-dependencies/swig 

I'm using that version of SWIG

With @diegoferigo we discovered that I had a leftover of a previous installation (it's strange that I was able to generate the bindings before). I'll modify the [guide](https://github.com/robotology/idyntree/blob/master/doc/generating-idyntree-matlab-bindings.md) specifying that in case of a different installation, SWIG folder should also specified.

**Pull request merged**
