### PR TITLE
Bindings for PredictSensorsMeasurement

### PR DESCRIPTION
**Pull request by naveenoid**
@nunoguedelha @traversaro Simply generated bindings..If you want I can write a simple test to show usage in matlab.

### CODE REVIEW

**Comment by traversaro** [comment]
What is the difference with the bindings already generated in the repo?

**Comment by naveenoid** [comment]
Ah didnt test it..I just wanted to make a PR with freshly made bindings and also push some tests on the PredictSenosrsMeasurement bindings..

**Comment by traversaro** [comment]
Apparently there was an addition of a method `Traversal::toString`, and hence the number of the methods changed... however whenever I do a PR I try to regenerate the bindings as the last step, otherwise the diff becomes unreadable (consider that anyway @nunoguedelha is able to generated bindings on its own).

**Comment by nunoguedelha** [comment]
Actually I had misunderstood the status of the predict measurements feature. I thought something else was missing beyond just rebuilding with the bindings activated on cmake. It had been a while I hadn't done it.

**Comment by nunoguedelha** [comment]
I pulled the branch. of course, a simple test to show usage in Matlab would be the most welcome. Thanks @naveenoid .

**Comment by traversaro** [comment]
Bindings regenerated in https://github.com/robotology/idyntree/pull/133 , closing this PR.

**Pull request closed without merging**
