### PR TITLE
Add option to build without icub-main

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
cc @EnricoMingo @arocchi

**Comment by arocchi** [comment]
Thank you @traversaro will check it next WE (together with the OpenSoT tests, and also a couple of timing tests to check if, for our usage, we have any performance issue)

**Comment by traversaro** [comment]
Perfect. By the way if you need to debug some performance issue I suggest the use of FlameGraph: http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html, a useful tool that I recently discovered.

**Comment by arocchi** [comment]
please take a look here https://github.com/arocchi/idyntree/tree/no_icub_fixes
I feel we are getting near, and the 3+ "no icub" branches soon will be forgotten past.

**Comment by arocchi** [comment]
Still have a problem related to sensors (it seems the code that uses the old iDyn now give a segmentation fault when trying to access the force/torque sensors)...
Any ideas @traversaro?

**Comment by traversaro** [comment]
It make sense... that was part of a quick refactor that we did at the summer school. It works for us because we always use the FT sensor related stuff using the TorqueEstimationTree class. Can you check if https://github.com/robotology/idyntree/commit/c82bb2cbdd1b52887af1223e89d24e3edfd7669c resolved the issue?

**Comment by arocchi** [comment]
@traversaro yes it did. Perfect, thank you. Did you take a look at e70d4e4227ac6d5458a6617f47cf217bc872dc5d ? Can't seem to compile without that. Of course you might want to make some of those changes conditional though :\

**Comment by traversaro** [comment]
@arocchi ah yes, the idyntree-yarp library should not link to icub (there is idyntree-icub for everything that needs icub!). Please open a PR, thanks.

**Comment by arocchi** [comment]
:+1:

**Pull request merged**
