### PR TITLE
Enable irrlicht dependency on CI and fix irrlicht use with vcpkg

### PR DESCRIPTION
**Pull request by traversaro**
This is done as now it is quite used downstream.

Fix https://github.com/robotology/idyntree/issues/756 .

### CODE REVIEW

**Comment by traversaro** [comment]
With respect to other dependencies, Irrlicht will remain disable unless the user explicitly enable it (see https://github.com/dic-iit/bipedal-locomotion-framework/pull/172) as it is not trivial to support if in the case of static linking.

**Comment by traversaro** [comment]
Irrlicht for now it is not enabled on conda as it is not available in conda-forge (for now, see https://github.com/conda-forge/staged-recipes/issues/13641).

**Review by prashanthr05 — APPROVED** [review]

**Review by S-Dafarra — APPROVED** [review]

**Comment by traversaro** [comment]
The CMake machinery needed a bit of refresh.

**Comment by traversaro** [comment]
I disabled the tests for now as on Ubuntu they need some sort of configuration, but on the Windows build I noticed that the Visualizer tests are failing but it seems a legit error:
~~~
106/114 Test #106: UnitTestVisualizer .............................................***Failed    0.35 sec
Irrlicht Engine version 1.8.4
 (Build 9200)
Using renderer: OpenGL 1.1.0
GDI Generic: Microsoft Corporation
OpenGL driver version is not 1.2 or better.
Failed to load OpenGL's multitexture extension, proceeding without.
Warning: OpenGL device only has one texture unit. Disabling multitexturing.
GLSL not available.
Resizing window (800 600)
Irrlicht Engine version 1.8.4
 (Build 9200)
Using renderer: OpenGL 1.1.0
GDI Generic: Microsoft Corporation
OpenGL driver version is not 1.2 or better.
Failed to load OpenGL's multitexture extension, proceeding without.
Warning: OpenGL device only has one texture unit. Disabling multitexturing.
GLSL not available.
Resizing window (800 600)
Irrlicht Engine version 1.8.4
 (Build 9200)
Using renderer: OpenGL 1.1.0
GDI Generic: Microsoft Corporation
OpenGL driver version is not 1.2 or better.
Failed to load OpenGL's multitexture extension, proceeding without.
Warning: OpenGL device only has one texture unit. Disabling multitexturing.
GLSL not available.
Resizing window (800 600)
Irrlicht Engine version 1.8.4
 (Build 9200)
Using renderer: OpenGL 1.1.0
GDI Generic: Microsoft Corporation
OpenGL driver version is not 1.2 or better.
Failed to load OpenGL's multitexture extension, proceeding without.
Warning: OpenGL device only has one texture unit. Disabling multitexturing.
GLSL not available.
Resizing window (800 600)
D:\a\idyntree\idyntree\src\visualization\tests\VisualizerUnitTest.cpp:110 : assertTrue failure
~~~

**Comment by traversaro** [comment]
Merging as this in any case is an improvement, we can track the test failures in https://github.com/robotology/idyntree/issues/808 .

**Comment by S-Dafarra** [comment]
> I disabled the tests for now as on Ubuntu they need some sort of configuration (see #808), but on the Windows build I noticed that the Visualizer tests are failing but it seems a legit error in https://github.com/robotology/idyntree/blob/devel/src/visualization/tests/VisualizerUnitTest.cpp#L110 :
> 
> ```
> 106/114 Test #106: UnitTestVisualizer .............................................***Failed    0.35 sec
> Irrlicht Engine version 1.8.4
>  (Build 9200)
> Using renderer: OpenGL 1.1.0
> GDI Generic: Microsoft Corporation
> OpenGL driver version is not 1.2 or better.
> Failed to load OpenGL's multitexture extension, proceeding without.
> Warning: OpenGL device only has one texture unit. Disabling multitexturing.
> GLSL not available.
> Resizing window (800 600)
> Irrlicht Engine version 1.8.4
>  (Build 9200)
> Using renderer: OpenGL 1.1.0
> GDI Generic: Microsoft Corporation
> OpenGL driver version is not 1.2 or better.
> Failed to load OpenGL's multitexture extension, proceeding without.
> Warning: OpenGL device only has one texture unit. Disabling multitexturing.
> GLSL not available.
> Resizing window (800 600)
> Irrlicht Engine version 1.8.4
>  (Build 9200)
> Using renderer: OpenGL 1.1.0
> GDI Generic: Microsoft Corporation
> OpenGL driver version is not 1.2 or better.
> Failed to load OpenGL's multitexture extension, proceeding without.
> Warning: OpenGL device only has one texture unit. Disabling multitexturing.
> GLSL not available.
> Resizing window (800 600)
> Irrlicht Engine version 1.8.4
>  (Build 9200)
> Using renderer: OpenGL 1.1.0
> GDI Generic: Microsoft Corporation
> OpenGL driver version is not 1.2 or better.
> Failed to load OpenGL's multitexture extension, proceeding without.
> Warning: OpenGL device only has one texture unit. Disabling multitexturing.
> GLSL not available.
> Resizing window (800 600)
> D:\a\idyntree\idyntree\src\visualization\tests\VisualizerUnitTest.cpp:110 : assertTrue failure
> ```
> 
> @S-Dafarra do you have any idea? Did you run it locally?

Sorry, I missed that. To be honest I did not test that functionality on Windows

**Comment by S-Dafarra** [comment]
I was expecting this check to fail first https://github.com/robotology/idyntree/blob/a88aacbae9e516c717c2e5d6a9293b7b0f78db0c/src/visualization/src/TexturesHandler.cpp#L37
but the warning of https://github.com/robotology/idyntree/blob/a88aacbae9e516c717c2e5d6a9293b7b0f78db0c/src/visualization/src/TexturesHandler.cpp#L81-L85 did not appear.

I wonder if it can still render to a texture, but the dimensions need to be the same of the main window: https://github.com/robotology/idyntree/blob/a88aacbae9e516c717c2e5d6a9293b7b0f78db0c/src/visualization/tests/VisualizerUnitTest.cpp#L93-L94

**Pull request merged**
