### PR TITLE
New joint system

### PR DESCRIPTION
**Pull request by traversaro**
The modification introduced in this pull request are still work in progress, but I would be happy if somebody (@nunoguedelha, @francesco-romano, @naveenoid ) started to have a look at it. 

Basically it is an attempt to introduced a joint system native to iDynTree (i.e. that can be easily wrapped by SWIG to Matlab/Python/Lua/..). 

Rough feature list is:
 * Support joints with an arbitrary number of DOFs (from 0 to 6). 
 * Support joints with a configuration spaces that is a non-euclidean manifold (not implemented by now, but the interface was designed to eventually support them).
 * Provide a undirected interface, i.e. the API providing information for a joint connecting linkA to linkB should be simmetric in the information that it can provides with respect to the two links. 

Inspirations for the design: 
 * [KDL Joints](https://github.com/orocos/orocos_kinematics_dynamics/blob/master/orocos_kdl/src/joint.hpp), the one that we used until now. 
 * [RBDL Joints](http://rbdl.bitbucket.org/df/dbe/joint_description.html)
 * [Simbody Joints](https://simtk.org/api_docs/simbody/latest/classSimTK_1_1MultibodyGraphMaker_1_1Mobilizer.html), probably the design from which I took more inspiration, look at http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3002261/ for a more scientific discussion of the topic. 
 * [DART joints](http://dartsim.github.io/dart/d6/d5b/classdart_1_1dynamics_1_1Joint.html)
 * The upcoming implementation of the C++ Joint system in Drake ( https://github.com/RobotLocomotion/drake/issues/1199 )  that support automatic differentiation. 

I plan not to commit the updated Matlab bindings until we merge the pull request, to keep the avoid rendering the pull request not readable .

### CODE REVIEW

**Comment by DanielePucci** [comment]
Sorry, but the third feature is not really clear to me (non expert user)  . May you exemplify it with an example?  Thank you!

**Comment by traversaro** [comment]
Most of existing kinematics/dynamics library model multibody systems as a directed tree (or graph, in case closed structures are supported). Following from that, the joints are model has having a "parent" and a "child" link, and their method return quantities using this assumptions.

 As an example, see the KDL::Joint : 
http://docs.ros.org/indigo/api/orocos_kdl/html/classKDL_1_1Joint.html#aa5710c751b86c5725091050327b80427

The `pose(const double & q)` returns the `parent_T_child` transform, and if you want instead the `child_T_parent

**Comment by DanielePucci** [comment]
Clear. Thanks.

**Comment by traversaro** [comment]
I think I will merge this PR with master to avoid balkanization of branches, and because I want to use the new testing infrastructure for the new features that we are adding to `DynamicsComputations` class with @prashanthr05 .

**Comment by traversaro** [comment]
We can resume any discussion in https://github.com/robotology/idyntree/issues/69 .

**Pull request merged**
