### PR TITLE
Use SDL for irrlicht visualizer on MacOS

### PR DESCRIPTION
**Pull request by lrapetti**
Fix https://github.com/robotology/idyntree/issues/1076

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Review by S-Dafarra — APPROVED** [review]

**Comment by lrapetti** [comment]
@traversaro I don't know if this change should be referred to as FIX rather than CHANGED in the changelog, since the visualizer is not working at all on MacOS in the `9.0.0` release.

**Comment by traversaro** [comment]
> @traversaro I don't know if this change should be referred to as FIX rather than CHANGED in the changelog, since the visualizer is not working at all on MacOS in the `9.0.0` release.

Yes, I think it make, sense, let me re-word also the sentence.

**Comment by traversaro** [comment]
> > @traversaro I don't know if this change should be referred to as FIX rather than CHANGED in the changelog, since the visualizer is not working at all on MacOS in the `9.0.0` release.
> 
> Yes, I think it make, sense, let me re-word also the sentence.

Let me know if the new sentence is ok.

**Comment by lrapetti** [comment]
> > > @traversaro I don't know if this change should be referred to as FIX rather than CHANGED in the changelog, since the visualizer is not working at all on MacOS in the `9.0.0` release.
> > 
> > 
> > Yes, I think it make, sense, let me re-word also the sentence.
> 
> Let me know if the new sentence is ok.

Looks good thanks @traversaro! I think we can merge it.

Maybe a release with the fix could make sense.

**Comment by traversaro** [comment]
> Maybe a release with the fix could make sense.

Done: https://github.com/robotology/idyntree/releases/tag/v9.1.0 .

**Pull request merged**
