### PR TITLE
 Add example on the use of the iDynTree.InverseKinematics class 

### PR DESCRIPTION
**Pull request by traversaro**
In particular, the example focus on solving the IK for an industrial manipulator.

### CODE REVIEW

**Comment by ahoarau** [comment]
Excellent ! Any benchmark available as well ?

**Comment by traversaro** [comment]
@AngeloRendiniello @InesSorrentino  the docs in the tutorial are clear? Or they could be improved in some way? 

> Excellent ! Any benchmark available as well ?

I need to check, I think there was something in the tests. For the sake of clarity I would avoid adding benchmarking code in the tutorial/examples.

**Comment by AngeloRendiniello** [comment]
For me and @InesSorrentino there were no problems in installing and testing this specific example: docs seems to be clear enough

**Comment by traversaro** [comment]
Ok, great.  Merging.

**Pull request merged**
