### PR TITLE
Added model tranformer functions

### PR DESCRIPTION
**Pull request by traversaro**
This new set of functions are an helper to modify `iDynTree::Model` for several use cases.

# removeFakeLinks : :white_check_mark: (implemented)
This function is used in the URDF parser to remove
"fake links" and transform them in "frames"

Added some frames as "fake links" to the oneLink.urdf
test model , to test the behaviour of this new function in
URDFModelImportUnitTest .

# createReducedModel :white_check_mark: (implemented)
This function will take in input a `iDynTree::Model` and
an ordered list of joints (in `std::vector<std::string>` form?)
and will return a model with just the joint specified in the list,
with that exact order. 

All other joints will be removed by lumping (i.e. fusing together)
the inertia of the links that are connected by that joint, assuming the joint 
to be in "rest" position (i.e. zero for revolute joints). The links eliminated 
with this process will be added back to the reduced model as "frames", 
and will be copied in the same way all the additional frames of the lumped links. 

This will be increasingly useful as we add more complex features to the iCub 
models (such as the hands, the ocular system), to avoid that function used 
by whole-body control are affected by this increasing complexity. In a nutshell, 
if we are controlling just 23 DOFs of the iCub, but we have a model with the full 53 DOFs, 
we should be able to run the RNEA or compute the mass matrix for just the DOFs that we use in control.

This function will be used for implementing the yarpWholeBodyModel use case 
(see https://github.com/robotology/idyntree/issues/93), in which the user specifies
only the DOFs that he is interested in, with the desired joint serialization. With respect
to the current implementation, in which a full model is used for computing all the dynamics matrices and algorithms (mass matrix, jacobian, etc etc) and then the mapping between the full dofs 
and the dofs considered by the user  is done  on the fly by the yarpWholeBodyModel (see for example https://github.com/robotology/yarp-wholebodyinterface/blob/master/src/yarpWholeBodyModel.cpp#L680 )
this should move all the logic from the runtime to the configuration time, with a gain both in the computational effort and on the effort necessary for the maintenance of the `yarpWholeBodyModel` class. 

This function can be used (as soon as we migrate the urdf export function to the new iDynTree classes) to provide a tool for solving

### CODE REVIEW

**Comment by traversaro** [comment]
cc @fiorisi for today's discussion on "fake links", if you are interested see https://github.com/robotology/idyntree/pull/103/files#diff-0adb5bef80354ab9aeb053217960483dR46 .

**Comment by traversaro** [comment]
To implement the `createReducedModel` function, I basically add to split up the model along the joints considered in the reduced model, and lump together in a single link the resulting submodels. 

This is similar to what we always have done for estimation of external forces and for identification of inertial parameters using 6 axis F/T sensors. For this reason I have implemented a first prototype of a `SubModelDecomposition` class in https://github.com/robotology/idyntree/commit/0bb76099a19656ff2e7911eae6dfa8a4e5be4cd6 . This class can be used to implement the `createReducedModel` , but also for https://github.com/robotology/idyntree/issues/97 .

The initial implementation includes a [`splitModelAlongJoints`](https://github.com/robotology/idyntree/commit/0bb76099a19656ff2e7911eae6dfa8a4e5be4cd6#diff-849be99354ec05a20795d3f681d16dd3R76) that will create a `SubModelDecomposition` algorithm by decomposing a model along the listed joints, basically a generalization of the old [buildSubGraphStructure](https://github.com/robotology/idyntree/blob/68a72ff18df1c85c6c85e04e8aa2da8f73368765/src/icub/src/TorqueEstimationTree.cpp#L336) used in the old TorqueEstimationTree class. 

In this new class, a `Traversal` class is associated to each subModel, containing a visit order for just the links contained in that SubModel . In this way the same algorithm can run on full `Model`s or on just a `SubModel` contained in the `SubModelDecomposition` class. My first use case for this is an algorithm to compute the Composite Rigid Body Inertia of a Traversal in the reference frame of its base, to compute the inertial parameters of the "lumped" links created by `createReducedModel`. 

I have also cleanup the Traversal method for simplify the implementation, so before merging this PR we need to regenerate the Matlab bindings. 

Note: I have used a `std::vector<std::string>` in the interface of the function. I think that in several case we will need function that take in input a list of "names", and so we should check that this is properly typemapped in the SWIG bindings (so in Python you could pass a list of string, or in Matlab a cell array of strings).  I would probably open an issue for this.

**Comment by traversaro** [comment]
I think it is better to try to close this PR (for the modifications in Traversal constructors) even before the `createReducedModel` is finished. Given that this will require regenerating the Matlab bindings, I think it is then convenient to merge also the "perfImprovements" branch, to avoid having to regenerate the matlab bindings multiple times in the same period. 

cc @nunoguedelha @naveenoid

**Comment by traversaro** [comment]
`createReducedModel` function implemented (with test added in `ModelUnitTest`) in https://github.com/robotology/idyntree/commit/23d637904bb67803dd184548ae4f485862eb9142 .

**Comment by naveenoid** [comment]
:+1:

**Pull request merged**
