### PR TITLE
Added possibility to change model and link colors in Meshcat visualizer

### PR DESCRIPTION
**Pull request by S-Dafarra**

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Any specific comment @GiulioRomualdi ?

**Review by GiulioRomualdi — APPROVED** [review]
That's nice! 
As far as I understood, this modification is backcompatible, right?

**Comment by S-Dafarra** [comment]
> That's nice! As far as I understood, this modification is backcompatible, right?

In theory yes. Clearly I might have introduced new bugs, but I tested it also with an ergoCub model and seems to behave as usual.

**Comment by traversaro** [comment]
Thanks! @S-Dafarra do you need a release?

**Comment by S-Dafarra** [comment]
> Thanks! @S-Dafarra do you need a release?

That would be nice, but not urgent. At the moment it would be a runtime dependency for an application introduced in https://github.com/ami-iit/hippopt/pull/16. So it is not blocking anyhow

**Pull request merged**
