### PR TITLE
Add KinDynComputations to the bindings and add example on how to get the axis of a joint expressed in a arbitary frame

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
@nunoguedelha @fjandrad Important change: I updated the swig-matlab commit that we use to generated the bindings to https://github.com/jaeandersson/swig/commit/5d3770e452b71265162001c2249dea7961660629 .

**Comment by traversaro** [comment]
The appveyor failure is related to Eigen on Visual Studio 2013, so I can safely merge.

**Comment by traversaro** [comment]
@TeoKa now that this is merged, can you update the `codyco-superbuild` (as described in https://github.com/robotology/codyco-superbuild#update ) and try this example : https://github.com/robotology/codyco-superbuild#update ?

**Comment by TeoKa** [comment]
thanks @traversaro. codyco-superbuild updated (and the code runs without problems).
Now, I try to become familiar with the code.

**Pull request merged**
