### PR TITLE
fix missing DOF_ACCELERATION to dynamic variable ordering

### PR DESCRIPTION
**Pull request by lrapetti**
The `DOF_ACCELERATION` is not add to the `dynamicVariablesOrdering`

### CODE REVIEW

**Comment by lrapetti** [comment]
CC @prashanthr05 @Yeshasvitvs

**Comment by traversaro** [comment]
Thanks @lrapetti , can you also update the changelog at https://github.com/robotology/idyntree/blob/devel/doc/releases/v0_12.md ? 

Furthermore, following Beyonce's Law: 
> "Cause if you like this code, then you shoulda put a test on it"
it would be nice to make sure that this code is tested, by generalizing the following test: https://github.com/robotology/idyntree/blob/master/src/estimation/tests/BerdyHelperUnitTest.cpp#L158 to the floating base case.

**Comment by lrapetti** [comment]
> Thanks @lrapetti , can you also update the changelog at https://github.com/robotology/idyntree/blob/devel/doc/releases/v0_12.md ?

done db0eefb9f41f7a2ece8abd046dda5be3aee52c53

**Comment by traversaro** [comment]
To clarify, fixing the test is not strictly required to get this PR merged.

**Comment by lrapetti** [comment]
> it would be nice to make sure that this code is tested, by generalizing the following test: https://github.com/robotology/idyntree/blob/master/src/estimation/tests/BerdyHelperUnitTest.cpp#L158 to the floating base case.

But is it also the test for fixed base currently commented out??https://github.com/robotology/idyntree/blob/master/src/estimation/tests/BerdyHelperUnitTest.cpp#L337-L341

**Comment by traversaro** [comment]
> But is it also the test for fixed base currently commented out??https://github.com/robotology/idyntree/blob/master/src/estimation/tests/BerdyHelperUnitTest.cpp#L337-L341

Good catch, I probably wrongly commented it out in and that slipped in in the review (probably due to the size, see https://github.com/robotology/idyntree/pull/356 and  https://twitter.com/iamdevloper/status/397664295875805184) . Actually  I opened an issue on this back in https://github.com/robotology/idyntree/issues/445 , this MAPest issue also seems related: https://github.com/claudia-lat/MAPest/issues/28 .

**Comment by traversaro** [comment]
@lrapetti I guess we can merge this PR even with no additional tests?

**Comment by lrapetti** [comment]
> @lrapetti I guess we can merge this PR even with no additional tests?

yess

**Pull request merged**
