### PR TITLE
Add Semantics checks to Transform class

### PR DESCRIPTION
**Pull request by nunoguedelha**
This change is a further step in the implementation of feature https://github.com/robotology/idyntree/issues/29, with a complete support of semantics in the Transform class.

Refactored Transform class:
- Transform is now only composed of Position and Rotation class objects, without duplicated semantics elements (every Transform semantics computation relies on Position and Rotation semantics operation methods)
- Transform support of semantics covers transformation of Position, Rotation and Transform. Semantics on Twist and Wrench will come in the next days.

**Note**: These changes are merged with implementation of Spatial Momentum, Spatial Acceleration and Spatial Inertia (https://github.com/robotology/idyntree/pull/59).

### CODE REVIEW

**Comment by traversaro** [comment]
LGTM, merging.

**Comment by traversaro** [comment]
Actually I just noted a possible problem: `TransformSemantics` class expose this two methods: 
 * `bool setRotationSemantics(const RotationSemantics & rotation);`
 * `bool setPositionSemantics(const PositionSemantics & position);`

One can call them on a transform using `transform.getSemantics().setRotationSemantics()`... However if they do like this they can have a inconsisteny between the sematics stored in `TransformSemantics` and the one store in the `Rotation` object stored in `Transform`.

**Comment by nunoguedelha** [comment]
Both methods from `TransformSemantics` ...
- `TransformSemantics::setRotationSemantics()`
- `TransformSemantics::setPositionSemantics()`

... as well as those from `Transform`...
- `Transform::setPosition()`
- `Transform::setRotation()`

... they all call `TransformSemantics::check_position2rotationConsistency()` which checks the consistency of semantics.
On top of that, `TransformSemantics::PositionSemantics` and `TransformSemantics::PositionSemantics` are references to the components semantics (`pos` and `rot`). These references are initialised once and for all by the constructors at Transform instantiation.

If I missed something, any comment is  most welcome.

**Comment by traversaro** [comment]
Ah yes, I forgot about the references in `TransformSemantics` (even if we already discussed them!) 
Sorry for the noise.

**Pull request merged**
