### PR TITLE
doxygen for Sensor expansion

### PR DESCRIPTION
**Pull request by naveenoid**
Doxygen working for Sensor expansion.

### CODE REVIEW

**Comment by traversaro** [comment]
The accelerometer class is non an interface (term topically used for pure virtual classes in C++, perhaps is best to rephrase the comment?

**Comment by traversaro** [comment]
@naveenoid  Anyway, for trivial task (documentation) were we don't risk to break the compilation feel free to commit directly to master, we can correct the documentation directly there. : )

**Comment by naveenoid** [comment]
@traversaro I just want to really get used to the correct way of doing things. I knew this was trivial but still. Especially given that its a core library to all our work.

**Comment by traversaro** [comment]
Ok!

**Pull request merged**
