### PR TITLE
Add octave support

### PR DESCRIPTION
**Pull request by traversaro**
war

Old branch, but it is time to revive it.

@DanielePucci @francesco-romano @iron76

### CODE REVIEW

**Comment by DanielePucci** [comment]
:D

**Comment by traversaro** [comment]
Added installation and tests (the same tests used for matlab run fine on octave). While some documentation in the README would be nice, this can be already merged at this point (in particular the octave testing in travis is quite convenient).

**Comment by traversaro** [comment]
There seems to be an XCode-related problem.

**Comment by traversaro** [comment]
The problem was with all multi-config CMake generators, fixed by https://github.com/robotology/idyntree/commit/51a69d8dd01e43949225a2e1665bff3cf938e50e . Merging.

**Pull request merged**
