### PR TITLE
Migrate to always use the Eigen3::Eigen imported target

### PR DESCRIPTION
**Pull request by traversaro**
Furthermore, modernize the involved CMake commands.

This will simplify the use of iDynTree in FetchContent-based build systems that use a non-imported Eigen3::Eigen and LibXml2::LibXml2 (for example when cross-compiling).

### CODE REVIEW

**Comment by traversaro** [comment]
> 
> 
> Probably this will have the side effect that many repositories will not compile anymore 😄

Why? Which kind of failure do you expect?

**Comment by GiulioRomualdi** [comment]
> Why? Which kind of failure do you expect?

Do you remember? Touching `Eigen` in `osqp-eigen` had the side effect that `iDynTree` and `WalkingControllers` didn't compile anymore.

**Comment by traversaro** [comment]
> 
> 
> > Why? Which kind of failure do you expect?
> 
> Do you remember? Touching `Eigen` in `osqp-eigen` had the side effect that `iDynTree` and `WalkingControllers` didn't compile anymore.

In that case I think it was due to the fact that `Eigen3::Eigen` was a public dependency, that is not the case for iDynTree so I expect less problems.

**Comment by traversaro** [comment]
This modifications exposed a bug in YCM (see https://github.com/robotology/ycm/pull/339) and its fix has been backported in this PR.

**Pull request merged**
