### PR TITLE
Bugfix in Span class

### LINKED ISSUE #729: Possible bug in iDynTree::Span
If I'm not mistaken here
https://github.com/robotology/idyntree/blob/f9fff5998c459dacf869629c3fe629d5831f240f/src/core/include/iDynTree/Core/Span.h#L498-L499

`double` should be substituted with `reference`.

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR should fix #729

### CODE REVIEW

**Comment by traversaro** [comment]
As we discussed in chat, could we use value type instead of const reference? This should fix the compilation failures of the bindings.

**Comment by GiulioRomualdi** [comment]
Actually, there is a bug in the code I proposed.
Indeed 
```cpp
typedef int& ref;
const ref error;
```
Doesn't do what I thought it does. For instance 
```cpp
typedef int* pointer;
typedef const pointer const_pointer;
```
the type `const_pointer` is **not** `const int *` but `int * const`. In case of pointers this is perfectly fine indeed:
- `const int *` this is a pointer to a const int  (you **cannot** change the value of the int but you **can** change the location of memory pointed by the pointer) 
- `int * const` this is a const pointer to an int (you **can** change the value of the int but you **cannot** change the location of memory pointed by the pointer)

However, the reference cannot be made `const` (or `volatile`). I.e.
```cpp
int& const x;
``` 
does not make any sense.

**Comment by traversaro** [comment]
In any case, using `value` would be coherent with the exiting code and fix the problem, right?

**Comment by GiulioRomualdi** [comment]
> In any case, using value would be coherent with the exiting code and fix the problem, right?

yes but that one is the reason why swig was failing

**Comment by traversaro** [comment]
> 
> 
> > In any case, using value would be coherent with the exiting code and fix the problem, right?
> 
> yes but that one is the reason why swig was failing

Ack!

**Review by traversaro — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
In https://github.com/robotology/idyntree/pull/749/commits/cc91f98cd42ddc20d068a7db78801e29f9ae725f I used the `value_type` instead of `reference`. Let's see now if `swig` complains

**Comment by GiulioRomualdi** [comment]
One of the tests is failing while compiling
 ```
/home/gromualdi/robot-code/robotology-superbuild/robotology/iDynTree/src/core/include/iDynTree/Core/Span.h: In instantiation of ‘class iDynTree::Span<int [3]>’:
/home/gromualdi/robot-code/robotology-superbuild/robotology/iDynTree/src/core/tests/SpanUnitTest.cpp:341:22:   required from here
/home/gromualdi/robot-code/robotology-superbuild/robotology/iDynTree/src/core/include/iDynTree/Core/Span.h:498:35: error: function returning an array
     IDYNTREE_CONSTEXPR value_type getVal(index_type idx) const { return this->operator[](idx);}
                                   ^~~~~~
/home/gromualdi/robot-code/robotology-superbuild/robotology/iDynTree/src/core/include/iDynTree/Core/Span.h: In instantiation of ‘class iDynTree::Span<int [3][2]>’:
/home/gromualdi/robot-code/robotology-superbuild/robotology/iDynTree/src/core/tests/SpanUnitTest.cpp:370:25:   required from here
/home/gromualdi/robot-code/robotology-superbuild/robotology/iDynTree/src/core/include/iDynTree/Core/Span.h:498:35: error: function returning an array
```

**Comment by traversaro** [comment]
Wow, I had no idea Span supported C-style arrays. Anyhow, in that case probably it make sense again to use const references as in your original proposal.

**Comment by GiulioRomualdi** [comment]
https://github.com/robotology/idyntree/pull/749/commits/26aa760bbe1c6a8ebb1ae430681799cf26c6ee4b fixes the bug. @traversaro let me know if I should change something, otherwise feel free to merge with squash

**Comment by traversaro** [comment]
Thanks @GiulioRomualdi !

**Pull request merged**
