### PR TITLE
External forces implementation without depending on yarp/icub/kdl

### PR DESCRIPTION
**Pull request by traversaro**
Sorry for the big PR, but we needed to fix https://github.com/robotology/idyntree/issues/97 soonish to start working on FT sensors calibration with @fjandrad .
The PR is huge, but I tried to do separate commits for different changes. The most important are:
* Refactor of Sensors in : https://github.com/robotology/idyntree/commit/7b7f6c35d51904b7327863644fbe46beef82ce7b and https://github.com/robotology/idyntree/commit/f3f9c33dbb829cccd52ac9bbc667673cb39369de 
  * Introduction of two different interfaces for Link and Joint sensors with specific methods
  * Added parsing of FT sensors from URDF using the URDF sensors proposal in place of the gazebo URDF extentions
  * Added FT sensors to predict sensors measurements
  * Refactor of the URDF sensors parsing code to reduce complexity and size of the code
* Implementation of class to estimate external contact wrenches 
* Implementation of conversion functions from/to the `skinDynLib` iCub library. 
* Implementation of a `ContactWrench` class to represent contact wrenches https://github.com/robotology/idyntree/commit/6ead0fad702ded04595b36a5792d8871f7019633 . To mark the difference between contact wrenches and **net** contact wrenches, the `LinkExternalWrenches` class has been renamed in `LinkNetExternalWrenches` https://github.com/robotology/idyntree/commit/29efe7d58ebe25826407c72be7498999aecddaaf .
* Add `reserve` methods to `VectorDynSize` https://github.com/robotology/idyntree/commit/29efe7d58ebe25826407c72be7498999aecddaaf and `MatridDynSize` classes https://github.com/robotology/idyntree/commit/06873d57c718da86cddf19c9a1c4087d93f29758 , to enable resizing of dynamics size matrices without dynamic memory allocation. 
* Move `estimation` , `yarp` and `icub` components to `estimation-kdl`, `yarp-kdl` and `icub-kdl` components, to mark the fact that they depend on KDL . Introduced new `estimation`, `yarp` and `icub` components to host code that does not depend on KDL  https://github.com/robotology/idyntree/commit/b5c89658458d823b06a01359108bac905c268f31 , https://github.com/robotology/idyntree/commit/1cef3728290c66f290bb781da1523d99c27ecbfb , https://github.com/robotology/idyntree/commit/90cd39639b40d0248b2af92ae6d6b18498264679 , https://github.com/robotology/idyntree/commit/d873c5bf5c49b0872fc106aec86acff9bab8d413 . 
* Added toString methods (useful for inspection and debug) to a bunch of classes : https://github.com/robotology/idyntree/commit/bbbee7e8eee8215b5a65faa565c333dc89cb1c3b , https://github.com/robotology/idyntree/commit/c4ec6f93369cd9382a18d16b53e41e233b42fedd
* Improvements to the `ClassicalAcc` class https://github.com/robotology/idyntree/commit/30f2d311c1e1000649bd2baa0e096b3981d429f6 
* And finally, the implementation of the external wrenches estimation described in http://www.researchgate.net/profile/Andrea_Del_Prete/publication/236152161_Contact_Force_Estimations_Using_Tactile_Sensors_and_Force__Torque_Sensors/links/00b495166e74a5369d000000.pdf https://github.com/robotology/idyntree/commit/31bbbedab8aef656f135f4c4cb1432398a2932c1 , https://github.com/robotology/idyntree/commit/db08f4a088e4c76f5adfd333914d1cb2ae5458e7 , https://github.com/robotology/idyntree/commit/df883c774a32c20649530c7fd0f95528ea1f3c6a .

### CODE REVIEW

**Comment by traversaro** [comment]
More relevant commits: 
* Added toString methods (useful for inspection and debug) to a bunch of classes : https://github.com/robotology/idyntree/commit/bbbee7e8eee8215b5a65faa565c333dc89cb1c3b , https://github.com/robotology/idyntree/commit/c4ec6f93369cd9382a18d16b53e41e233b42fedd
* Improvements to the `ClassicalAcc` class https://github.com/robotology/idyntree/commit/30f2d311c1e1000649bd2baa0e096b3981d429f6 
* And finally, the implementation of the external wrenches estimation described in http://www.researchgate.net/profile/Andrea_Del_Prete/publication/236152161_Contact_Force_Estimations_Using_Tactile_Sensors_and_Force__Torque_Sensors/links/00b495166e74a5369d000000.pdf https://github.com/robotology/idyntree/commit/31bbbedab8aef656f135f4c4cb1432398a2932c1 , https://github.com/robotology/idyntree/commit/db08f4a088e4c76f5adfd333914d1cb2ae5458e7 , https://github.com/robotology/idyntree/commit/df883c774a32c20649530c7fd0f95528ea1f3c6a .

**Comment by naveenoid** [comment]
Im checking the Sensors stuff...

On Fri, Jan 22, 2016 at 5:02 PM, Silvio Traversaro <notifications@github.com

**Comment by traversaro** [comment]
`ExtWrenchesAndJointTorquesEstimator` class (meant to be the interface to the external wrenches and joint torques estimation for end user) added in https://github.com/robotology/idyntree/commit/61a8c4fe81f9589647f8e9dc592199cad1863a87 .

**Comment by traversaro** [comment]
There is still a failing Valgrind test (see https://travis-ci.org/robotology/idyntree/builds/104753362), in the meanwhile @fjandrad can you start having a look to the class API https://github.com/robotology/idyntree/commit/61a8c4fe81f9589647f8e9dc592199cad1863a87 ?

**Comment by traversaro** [comment]
Still some issues related to compilation on Windows : ( 
@fjandrad In the meanwhile you can already have a look at the matlab code looking at : https://github.com/robotology/idyntree/blob/d8ef724b103083116c57ec00eb11ea3f5d0a12f3/examples/matlab/SixAxisFTOffsetEstimation/SixAxisFTOffsetEstimation.m .

**Comment by traversaro** [comment]
All tests passing, merging.

**Comment by naveenoid** [comment]
:+1 Sensors and associated classes look solid.

On Thu, Jan 28, 2016 at 2:44 PM, Silvio Traversaro <notifications@github.com

**Comment by naveenoid** [comment]
@traversaro Did you push in a new URDF with FT sensors using sensor tags?

**Comment by traversaro** [comment]
@naveenoid In the test URDF in https://github.com/robotology/idyntree/commit/f3f9c33dbb829cccd52ac9bbc667673cb39369de#diff-a5b51a164cafbfc837fe4431883374dcL1289 , in the urdf for the robots for now only on iCubGenova02 in https://github.com/robotology/yarp-wholebodyinterface/commit/d445b9081126b08fdec41b916231a54cd507b717 .

**Pull request merged**
