### PR TITLE
GitHub Actions: Enable IPOPT tests on macOS

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
The tests runs, but for some strange reason. It seems that for some reason ipopt is searching for the ma27 linear solver, that clearly is distributed with homebrew.

**Comment by traversaro** [comment]
Apparently the tests on macOS are failing with:
~~~
Exception of type: OPTION_INVALID in file "IpAlgBuilder.cpp" at line 268:
 Exception message: Selected linear solver MA27 not available.
Tried to obtain MA27 from shared library "libhsl.dylib", but the following error occured:
dlopen(libhsl.dylib, 2): image not found

EXIT: Invalid option encountered.
/Users/runner/work/idyntree/idyntree/src/optimalcontrol/tests/IpoptInterfaceTest.cpp:214 : assertTrue failure

      Start 51: UnitTestOptimalControlIpopt
51/57 Test #51: UnitTestOptimalControlIpopt ...........................***Failed    0.05 sec
~~~
It seems that for some reason the Ipopt is configured to use the MA27 linear solver, that is however a linear solver that is not redistributable and for that reason is not used and shipped with IPOPT by default. The strange thing is that BLF seems to have tests that use IPOPT on macOS, and in the past @lrapetti and @claudia-lat used the IPOPT-based IK of iDynTree  with no problem. To add more mistery, all occurences of that error that is possible to found of internet report of similar problems that homebrew users were experiencing in 2012/2014.

**Comment by lrapetti** [comment]
> in the past @lrapetti and @claudia-lat used the IPOPT-based IK of iDynTree with no problem

I confirm we used it in the past. If I am not wrong the default solver was `mumps` that is installed with `homebrew`.
I went trough the tests and it doesn't seem to be setting any specific solver a part from the commented on at https://github.com/robotology/idyntree/blob/d5bbceab9e8ae52943b31199f6e024d12ff52159/src/optimalcontrol/tests/OptimalControlIpoptTest.cpp#L258.

**Comment by traversaro** [comment]
A MA27-related problem is mentioned in https://github.com/RobotLocomotion/drake/pull/14288 .

**Comment by traversaro** [comment]
I think this error was solved by https://github.com/Homebrew/homebrew-core/pull/64108 .

**Comment by lrapetti** [comment]
> I think this error was solved by [Homebrew/homebrew-core#64108](https://github.com/Homebrew/homebrew-core/pull/64108) .

The changes should have been merged (https://github.com/Homebrew/homebrew-core/commit/22717d993c90aca974a85cc68ae6bca15e422683), @traversaro can you trigger a new run of the CI tests?

**Review by lrapetti — APPROVED** [review]

**Comment by traversaro** [comment]
> > I think this error was solved by [Homebrew/homebrew-core#64108](https://github.com/Homebrew/homebrew-core/pull/64108) .
> 
> The changes should have been merged ([Homebrew/homebrew-core@22717d9](https://github.com/Homebrew/homebrew-core/commit/22717d993c90aca974a85cc68ae6bca15e422683)), @traversaro can you trigger a new run of the CI tests?


It seems that the problem is still there, not sure if the bottle needs to be updated or if there are other problems.

**Comment by traversaro** [comment]
Now the mumps solver is found correctly, the only test that is failing is:

~~~
50/57 Test #50: UnitTestIpoptInterface ................................***Failed    0.11 sec

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

/Users/runner/work/idyntree/idyntree/src/optimalcontrol/tests/IpoptInterfaceTest.cpp:217 : assertDoubleAreEqual failure: val1 is 519.635 while val2 is 519.635
~~~

However, this could be just a slight change due to some difference in the underlying math libraries, that could be solved by slightly increasing the tolerance.

**Comment by traversaro** [comment]
Thanks for the patience @lrapetti .

**Pull request merged**
