### PR TITLE
Addition of BoundingBoxProjectionConstraint

### PR DESCRIPTION
**Pull request by jeljaik**
A class similar to ConvexHullProjectionConstraint has been added with which a bounding box parallel to the axes can be created and added as constraint.

### CODE REVIEW

**Comment by traversaro** [comment]
I guess you wanted to target `devel` ?

**Comment by jeljaik** [comment]
Yes, my bad. Changed.

**Comment by traversaro** [comment]
Either @S-Dafarra or @aikolina are up for a review? Thanks!

**Comment by S-Dafarra** [comment]
I tested it and seems to be working fine!

**Comment by traversaro** [comment]
Thanks @S-Dafarra , if you reviewed the PR please approve it!

**Comment by traversaro** [comment]
Thanks, feel free to track those improvements in separated issues.

**Comment by jeljaik** [comment]
Thanks everyone

**Pull request merged**
