### PR TITLE
Fix frame export for multi-root models.

### PR DESCRIPTION
**Pull request by francesco-romano**
Do not export frames if corresponding link is not in the traversal.
This can happen if the model has links (and frames attached to those links) that
are not present in the exported traversal.

### CODE REVIEW

**Review by traversaro — APPROVED** [review]
Thanks, the fix seems nice. I just changed a bit the changelog style to match the rest of the document.

**Comment by traversaro** [comment]
There seems to be a memory-related error of some kind.

**Comment by francesco-romano** [comment]
I am not sure if the fix worked. Can you please take a look at it?

**Comment by traversaro** [comment]
> 
> 
> I am not sure if the fix worked. Can you please take a look at it?

The tests are green it seems, so it seems fine.

**Pull request merged**
