### PR TITLE
enable IDYNTREE_USES_OCTAVE in MacOS CI

### PR DESCRIPTION
**Pull request by lrapetti**
Enabling `IDYNTREE_USES_OCTAVE` in MacOS CI will avoid regression such as https://github.com/robotology/idyntree/issues/675

### CODE REVIEW

**Comment by lrapetti** [comment]
Probably should enable `OCTAVE` not `MATLAB`, I will update it

**Comment by traversaro** [comment]
It seems that Octave installed by the Homebrew is correctly found (otherwise the version would not be the correct one), but apparently something is missing: 
~~~
CMake Error at /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Octave (missing: OCTAVE_ROOT_DIR) (found version "5.2.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.0_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOctave.cmake:161 (find_package_handle_standard_args)
  bindings/matlab/CMakeLists.txt:133 (find_package)
~~~~
Unfortunately I don't have access to macOS, but if you have and you can `brew install octave` locally, and open a terminal and execute `octave-config -p PREFIX` and tell me the output it would be great.

**Comment by lrapetti** [comment]
> That is strange, can you also copy the output of `octave-config -h` , `octave-config -v` and `octave-config --m-site-dir` ?

```
$ octave-config -h
usage: octave-config [options]

Options:

  -h, -?, --help        Print this message.

  --m-site-dir          Print the name of the directory where Octave
                        expects to find locally installed .m files.

  --oct-site-dir        Print the name of the directory where Octave
                        expects to find locally installed .oct files.

  -p VAR, --print VAR   Print the value of the given configuration
                        variable VAR.  Recognized variables are:

                          API_VERSION            LOCALFCNFILEDIR
                          ARCHLIBDIR             LOCALOCTFILEDIR
                          BINDIR                 LOCALSTARTUPFILEDIR
                          CANONICAL_HOST_TYPE    LOCALVERARCHLIBDIR
                          DATADIR                LOCALVERFCNFILEDIR
                          DATAROOTDIR            LOCALVEROCTFILEDIR
                          DEFAULT_PAGER          MAN1DIR
                          EXEC_PREFIX            MAN1EXT
                          EXEEXT                 MANDIR
                          FCNFILEDIR             OCTAVE_EXEC_HOME
                          IMAGEDIR               OCTAVE_HOME
                          INCLUDEDIR             OCTDATADIR
                          INFODIR                OCTDOCDIR
                          INFOFILE               OCTFILEDIR
                          LIBDIR                 OCTFONTSDIR
                          LIBEXECDIR             OCTINCLUDEDIR
                          LOCALAPIARCHLIBDIR     OCTLIBDIR
                          LOCALAPIFCNFILEDIR     STARTUPFILEDIR
                          LOCALAPIOCTFILEDIR     VERSION
                          LOCALARCHLIBDIR

  -v, --version         Print the Octave version number.


$ octave-config -v
5.2.0


$ octave-config --m-site-dir
/usr/local/Cellar/octave/5.2.0_7/share/octave/5.2.0/site/m
```

**Comment by traversaro** [comment]
For reference, this is the output of the `octave-config -h` on my Ubuntu 18.04, Octave 4.2.2 : 
~~~
straversaro@IITICUBLAP102:~$ octave-config -h
usage: octave-config [options]

Options:

  -h, -?, --help        Print this message.

  --m-site-dir          Print the name of the directory where Octave
                        expects to find locally installed .m files.

  --oct-site-dir        Print the name of the directory where Octave
                        expects to find locally installed .oct files.

  -p VAR, --print VAR   Print the value of the given configuration
                        variable VAR.  Recognized variables are:

                          API_VERSION            LOCALARCHLIBDIR
                          ARCHLIBDIR             LOCALFCNFILEDIR
                          BINDIR                 LOCALOCTFILEDIR
                          CANONICAL_HOST_TYPE    LOCALSTARTUPFILEDIR
                          DATADIR                LOCALVERARCHLIBDIR
                          DATAROOTDIR            LOCALVERFCNFILEDIR
                          DEFAULT_PAGER          LOCALVEROCTFILEDIR
                          EXEC_PREFIX            MAN1DIR
                          EXEEXT                 MAN1EXT
                          FCNFILEDIR             MANDIR
                          IMAGEDIR               OCTDATADIR
                          INCLUDEDIR             OCTFILEDIR
                          INFODIR                OCTINCLUDEDIR
                          INFOFILE               OCTLIBDIR
                          LIBDIR                 PREFIX
                          LIBEXECDIR             STARTUPFILEDIR
                          LOCALAPIARCHLIBDIR     VERSION
                          LOCALAPIFCNFILEDIR
                          LOCALAPIOCTFILEDIR

  -v, --version         Print the Octave version number.

straversaro@IITICUBLAP102:~$ octave-config -v
4.2.2
straversaro@IITICUBLAP102:~$
~~~
 
So I guess that for some reason the `PREFIX`  variable either has been remove in Octave 5, or it has been removed on macOS. In any case, the `OCTAVE_ROOT_DIR`  is not actually used in any of our CMake scripts, so we can just remove the lines related to `OCTAVE_ROOT_DIR` from https://github.com/robotology/idyntree/blob/master/cmake/FindOctave.cmake (especially the fact that it is passed as "REQUIRED_VARS"  to `find_package_handle_standard_args` , that is the thing that is actually making the `find_package(Octave REQUIRED)` fail, and everything should work fine.

**Comment by traversaro** [comment]
Indeed, the support for the `PREFIX` variable was removed in https://github.com/NexMirror/Octave/commit/533db703ce624136b439a19a41f406a8772b9aad#diff-659cce8e2827126070ace2206360d607 .

**Comment by traversaro** [comment]
Related issues: 
* https://github.com/robotology/ycm/issues/193
* https://github.com/robotology/robotology-superbuild/issues/290

**Comment by lrapetti** [comment]
> So I guess that for some reason the `PREFIX` variable either has been remove in Octave 5, or it has been removed on macOS. In any case, the `OCTAVE_ROOT_DIR` is not actually used in any of our CMake scripts, so we can just remove the lines related to `OCTAVE_ROOT_DIR` from https://github.com/robotology/idyntree/blob/master/cmake/FindOctave.cmake (especially the fact that it is passed as "REQUIRED_VARS" to `find_package_handle_standard_args` , that is the thing that is actually making the `find_package(Octave REQUIRED)` fail, and everything should work fine.

so you would completely remove it or make it somehow optional?

**Comment by traversaro** [comment]
> 
> 
> > So I guess that for some reason the `PREFIX` variable either has been remove in Octave 5, or it has been removed on macOS. In any case, the `OCTAVE_ROOT_DIR` is not actually used in any of our CMake scripts, so we can just remove the lines related to `OCTAVE_ROOT_DIR` from https://github.com/robotology/idyntree/blob/master/cmake/FindOctave.cmake (especially the fact that it is passed as "REQUIRED_VARS" to `find_package_handle_standard_args` , that is the thing that is actually making the `find_package(Octave REQUIRED)` fail, and everything should work fine.
> 
> so you would completely remove it or make it somehow optional?

Let's completely remove, the `FindOctave` is just  used in iDynTree and not installed, so we don't care.

**Comment by lrapetti** [comment]
> > > So I guess that for some reason the `PREFIX` variable either has been remove in Octave 5, or it has been removed on macOS. In any case, the `OCTAVE_ROOT_DIR` is not actually used in any of our CMake scripts, so we can just remove the lines related to `OCTAVE_ROOT_DIR` from https://github.com/robotology/idyntree/blob/master/cmake/FindOctave.cmake (especially the fact that it is passed as "REQUIRED_VARS" to `find_package_handle_standard_args` , that is the thing that is actually making the `find_package(Octave REQUIRED)` fail, and everything should work fine.
> > 
> > 
> > so you would completely remove it or make it somehow optional?
> 
> Let's completely remove, the `FindOctave` is just used in iDynTree and not installed, so we don't care.

I have removed it in https://github.com/robotology/idyntree/pull/677/commits/571744fa4bf771b0fb755ef9f616d05d371c7b06, please @traversaro check if it sounds correct to you

**Comment by traversaro** [comment]
Great, it is working fine, thanks!

**Pull request merged**
