### PR TITLE
Fix getAxis implementation in Revolute and Prismatic Joint and documentation cleanup

### PR DESCRIPTION
**Pull request by traversaro**
The direction of the axis in a joint depends on which body
you consider parent and which body you consider child .

 Seth, A., Sherman, M., Eastman, P., & Delp, S. (2010).
 Minimal formulation of joint motion for biomechanisms.
 Nonlinear Dynamics, 62(1), 291-303.
 https://nmbl.stanford.edu/publications/pdf/Seth2010.pdf
 Section 2.4

 and

 "Modelling, Estimation and Identification of Humanoid Robots Dynamics"
 Traversaro - Section 3.2
 https://traversaro.github.io/preprints/traversaro-phd-thesis.pdf

 for more details.

This is a small change, but it is extremely important.
I hope that the additional documentation will help document it.

A few additional methods for the Direction and the Axis class leaked in from the bigger PR I am preparing to address https://github.com/robotology/idyntree/issues/340 , I hope they do not complicate the review too much.

### CODE REVIEW

**Comment by traversaro** [comment]
I just noticed that I also fixed the computation of the motion subspace vectors for the prismatic joint in 
`resetAxisBuffers` @Yeshasvitvs . Sorry for the huge PR.

**Comment by traversaro** [comment]
The test that revealed this would be included in the following PR, addressing https://github.com/robotology/idyntree/issues/340 .

**Comment by traversaro** [comment]
I need to proceed with https://github.com/robotology/idyntree/issues/340 , so I am going to merge this. But @DanielePucci please remember to get someone to understand this PR!

**Comment by DanielePucci** [comment]
Yes @traversaro : @nunoguedelha, @fjandrad , and @diegoferigo can you make a small team to dig into this pull request?  

Thanks!

**Comment by DanielePucci** [comment]
The idea of the small team is to speed up the comprehension of the PR, which shall not take more than one-working day, and thus not requiring any blocking of the on-going activities. 

This micro-activity has small priority, but it must be accomplished by mid of September. 

Thank you guys.

**Comment by fjandrad** [comment]
@nunoguedelha @diegoferigo @traversaro Shall we try the small team PR review?

**Pull request merged**
