### PR TITLE
Fix generation of Matlab bindings

### PR DESCRIPTION
**Pull request by traversaro**
ref #136

### CODE REVIEW

**Comment by traversaro** [comment]
I tested on Linux and OS X, this solves  https://github.com/robotology/idyntree/issues/136 (I don't have any idea how it was possible that it was working before).
I will modify the iDynTree.i  to include some files that are missing (and solve https://github.com/robotology/idyntree/issues/139) to regenerate the bindings only once.

**Comment by nunoguedelha** [comment]
@traversaro , the additional header I would need for getting the transforms in Matlab is the `iDynTree/Model/ForwardKinematics.h`.
Thx!

**Comment by traversaro** [comment]
While I was at it, I also: 
  * Fixed the fact that getLink / getJoint were not callable by bindings [ https://github.com/robotology/idyntree/commit/c9260c53a3f0e76a35e7d21f678bfa5154902dfe ] 
  * Fix python tests  [ https://github.com/robotology/idyntree/commit/29671c01d54d0092da0ee1ae6fda6b9642496de4 ] 
  * Added instantiaion of vector<string> [ https://github.com/robotology/idyntree/commit/cf5faf9c29428aaed5028bacf2f89c000a7cdda7 ] 
 * Added bindings-friendly getters to SensorList [ https://github.com/robotology/idyntree/commit/45985fb8400369d2964ff0d77813c355ed5c5b74 ]

**Comment by traversaro** [comment]
@kjyv  I already included some of your modification, It should not be a problem merging with your branch.

**Comment by traversaro** [comment]
I will wait for Travis/AppVeyor to compile and then I will regenerate the bindings and push. @nunoguedelha do you want to have a look at the changes?

**Comment by nunoguedelha** [comment]
already doing so :)

**Comment by nunoguedelha** [comment]
:+1:

**Pull request merged**
