### PR TITLE
Make sure that pip is aware of the idyntree Python package if iDynTree is installed just via CMake

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/robotology-superbuild/issues/1012 for what regards iDynTree.

### CODE REVIEW

**Review by diegoferigo — APPROVED** [review]
Cool, did you try to check what's happens with `pip uninstall idyntree`?

**Comment by traversaro** [comment]
> Cool, did you try to check what's happens with `pip uninstall idyntree`?

In this version, it prints a scary error:
~~~
traversaro@IITICUBLAP257:~/idyntree/bb$ pip uninstall idyntree
Found existing installation: idyntree 4.3.1
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/uninstall.py", line 78, in run
    uninstall_pathset = req.uninstall(
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_uninstall.py", line 535, in from_dist
    for path in uninstallation_paths(dist):
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_uninstall.py", line 67, in unique
    for item in fn(*args, **kw):
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_uninstall.py", line 85, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1433, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1421, in get_metadata
    value = self._get(path)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1617, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/traversaro/idyntree/bb/install/lib/python3/dist-packages/idyntree-4.3.1.dist-info/RECORD'
~~~~

While for apt-installed packages such as `numpy` it prints a more clear:
~~~
traversaro@IITICUBLAP257:~/idyntree/bb$ pip uninstall numpy
Found existing installation: numpy 1.17.4
Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'numpy'. No files were found to uninstall.
~~~

By adding an empty `RECORD` file in , the error message is more clear also for iDynTree:
~~~
traversaro@IITICUBLAP257:~/idyntree/bb$ pip uninstall idyntree
Found existing installation: idyntree 4.3.1
Can't uninstall 'idyntree'. No files were found to uninstall.
~~~

If one wants to be fancy, you can also install a `INSTALLER` file in `idyntree-4.3.1.dist-info` with the `cmake` string in it, so that the line printed by `pip list --verbose | grep idyntree` is:
~~~
Package                Version              Location                                                       Installer
idyntree               4.3.1                /home/traversaro/idyntree/bb/install/lib/python3/dist-packages cmake
~~~

**Comment by traversaro** [comment]
> In this version, it prints a scary error:

However, the scary message I think is a Python bug, the specs are quite clear in specifying that only `METADATA` is compulsory.

**Comment by traversaro** [comment]
> > In this version, it prints a scary error:
> 
> However, the scary message I think is a Python bug, the specs are quite clear in specifying that only `METADATA` is compulsory.

Indeed, by trying with a recent pip (22.0.1) the message if no RECORD is not found is clear:
~~~
(piptest) traversaro@IITICUBLAP257:~/idyntree/bb$ pip uninstall idyntree
Found existing installation: idyntree 4.3.1
ERROR: Cannot uninstall idyntree 4.3.1, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps idyntree==4.3.1'.
~~~

However, the hint is wrong as it would substitute the cmake installed idyntree with the pypi one. A much better message error is given if you provide an `INSTALLER` file:
~~~
(piptest) traversaro@IITICUBLAP257:~/idyntree/bb$ pip uninstall idyntree
Found existing installation: idyntree 4.3.1
ERROR: Cannot uninstall idyntree 4.3.1, RECORD file not found. Hint: The package was installed by cmake.
~~~

I think this is a good reason to add an `INSTALLER` file.

**Pull request merged**
