### PR TITLE
Add new Matlab versions to MATLAB_VERSIONS_MAPPING

### PR DESCRIPTION
**Pull request by lrapetti**
Adding missing version of Matlab in `FindMatlab.cmake` (analogous to https://github.com/robotology/yarp-matlab-bindings/pull/81#event-6127048568)

### CODE REVIEW

**Comment by lrapetti** [comment]
cc @traversaro

**Review by traversaro — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks! Yet another local copy of FindMatlab that it is a good idea to remove.

**Comment by lrapetti** [comment]
@traversaro are those changes affecting only MacOS user? Because It seems I am the only one experiencing the issue

**Comment by traversaro** [comment]
> @traversaro are those changes affecting only MacOS user? Because It seems I am the only one experiencing the issue

It may be. Which kind of issue are you experiencing in particular?

**Comment by lrapetti** [comment]
> > @traversaro are those changes affecting only MacOS user? Because It seems I am the only one experiencing the issue
> 
> It may be. Which kind of issue are you experiencing in particular?

Same issue experienced by @kouroshD in https://github.com/robotology/yarp-matlab-bindings/issues/40 (he was on MaxOS as well)

**Comment by traversaro** [comment]
> > > @traversaro are those changes affecting only MacOS user? Because It seems I am the only one experiencing the issue
> > 
> > 
> > It may be. Which kind of issue are you experiencing in particular?
> 
> Same issue experienced by @kouroshD in [robotology/yarp-matlab-bindings#40](https://github.com/robotology/yarp-matlab-bindings/issues/40) (he was on MacOS as well)

Yes, I think this part of the code is the problem is https://github.com/Kitware/CMake/blob/v3.22.2/Modules/FindMatlab.cmake#L1408 . On macOS the version numbers supported are needed to look for matlab itself.

**Pull request merged**
