### PR TITLE
Fix use of constructors of Joint classes in bindings

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/idyntree/issues/424 , by solving the confusing definition of a method that was confusing swig ( https://github.com/robotology/idyntree/commit/175aaf1c31a36b514ebf4869ae1a8e177f06128c ) and by adding PrismaticJoint to the bindings ( https://github.com/robotology/idyntree/commit/1944e4ed6a948443822a114e55ac24bb6ecac19f ).
Added some tests to avoid future regressions ( https://github.com/robotology/idyntree/commit/76ba580d0a353477091e72e11fdda12c9272b232 ). 
Regenerate the matlab bindings ( https://github.com/robotology/idyntree/commit/c25bb2a2aeeb7d383ba3ff9324bae085d54b4b57 )

### CODE REVIEW

**Comment by traversaro** [comment]
@aikolina 
for testing this, add my fork of the repo as remote in your idyntree local repository and checkout the `fix/424` branch:
~~~
git remote add traversaro-fork https://github.com/traversaro/idyntree
git fetch traversaro-fork
git checkout fix/424
~~~

**Comment by traversaro** [comment]
Thanks nuno, merging.

**Comment by traversaro** [comment]
@aikolina The fix should be available in the `devel` branch of idyntree.

**Comment by aikolina** [comment]
@traversaro Sorry for the delay!
I tested your fork, and both the Revolute and Prismatic Joint constructors work correctly now. Thanks!

**Pull request merged**
