### PR TITLE
Add non collocated external wrenches estimation Berdy variant

### PR DESCRIPTION
**Pull request by RiccardoGrieco**
This PR adds a new variant to the Berdy MAP Estimator for estimating the external wrenches acting on a multi-rigid body, which is the relation (25b) of https://ieeexplore.ieee.org/abstract/document/9526592.

The PR adds a new fictitious sensor for the Rate of Change of Momentum (RCM), which provides a new measurement for the berdy problem.

### ⚠️ WARNING
The Rate of Change of Momentum (RCM) should be computed in the CoM as per https://ieeexplore.ieee.org/abstract/document/9526592, but here the adjoint wrench transforms related to the RCM are not from the i-th link to the centroidal frame, but to the base one. For this reason `Y*d` will compute the sum of the estimated external wrenches transformed in the base frame, not the centroidal one. 

For this reason, the measurement of the fictitious sensor should account for the bias terms generated by this transformation.

### CODE REVIEW

**Comment by RiccardoGrieco** [comment]
cc @traversaro

**Comment by RiccardoGrieco** [comment]
@traversaro the PR is ready to be reviewed. 

I suppose that the one check that is not completed is due to the fact that the commit where the matlab bindings have been regenerated are authored by a github action so we can ignore it.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks, this seems nice! 

Remaining points:
* Do you want to curate the commits or I can merge with "Squash and merge"?
* Can you add something on the ChangeLog related to this? In particular, it is important to document that the signature of the `BerdyHelper::serializeDynamicVariables` method changed, so downstream users need to change how they call it.

**Comment by RiccardoGrieco** [comment]
> * Can you add something on the ChangeLog related to this? In particular, it is important to document that the signature of the `BerdyHelper::serializeDynamicVariables` method changed, so downstream users need to change how they call it.

Thanks, I didn't think about that. Added in [8dab362](https://github.com/robotology/idyntree/pull/991/commits/8dab36252a27197c4d94346033a76f2f88576627).

> * Do you want to curate the commits or I can merge with "Squash and merge"?

You can proceed with "Squash and merge"!

**Pull request merged**
