### PR TITLE
Implement get_random_chain and get_random_model pybind11 bindings

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This should simplify the test written by @paolo-viceconte in https://github.com/dic-iit/bipedal-locomotion-framework/pull/303#discussion_r631009071

### CODE REVIEW

**Review by diegoferigo — APPROVED** [review]
This PR is ok, but remember that the official bindings are those generated by SWIG. AFAIK only @francesco-romano is using those generated by pybind11, and they only bind a small subset of classes.

**Review by francesco-romano — COMMENTED** [review]
Strange that also the original iDynTree C++ function is not in a `testing` namespace.
Do you think it makes sense to have a separate python module for that?

But this is just a question. Feel free to discard / do it in a second stage.

**Comment by GiulioRomualdi** [comment]
Hi @francesco-romano 

> Strange that also the original iDynTree C++ function is not in a `testing` namespace.
> Do you think it makes sense to have a separate python module for that?

I was wondering exactly the same.  I don't know if this can be done before releasing iDynTree 4. Probably @traversaro can jump in 😄

**Comment by francesco-romano** [comment]
> Hi @francesco-romano
> 
> > Strange that also the original iDynTree C++ function is not in a `testing` namespace.
> > Do you think it makes sense to have a separate python module for that?
> 
> I was wondering exactly the same. I don't know if this can be done before releasing iDynTree 4. 
> Probably @traversaro can jump in 😄

It might be because at some time we tried to flatten the namespace as to make it "friendly" to macOS frameworks. -- I think --

**Comment by traversaro** [comment]
> 
> 
> > Hi @francesco-romano
> > > Strange that also the original iDynTree C++ function is not in a `testing` namespace.
> > > Do you think it makes sense to have a separate python module for that?
> > 
> > 
> > I was wondering exactly the same. I don't know if this can be done before releasing iDynTree 4.
> > Probably @traversaro can jump in 😄
> 
> It might be because at some time we tried to flatten the namespace as to make it "friendly" to macOS frameworks. -- I think --

Yes, there was a mixture of reasons, actually most classes of iDynTree are just under the `iDynTree` namespace (think `iDynTree::KinDynComputations`). The main reason back in time was to have an easier parallel with MATLAB bindings, in which we just had the `iDynTree` namespace even if at the C++ level there were multiple namespace.

**Review by traversaro — APPROVED** [review]
This PR seems fine, as @diegoferigo mentioned if we want to use the pybind11-bindings of iDynTree directly in blf we may need to understand a bit how to deal with it from the deployment point of view, but I think this does not prevent to merge this PR.

**Comment by diegoferigo** [comment]
> This PR seems fine, as @diegoferigo mentioned if we want to use the pybind11-bindings of iDynTree directly in blf we may need to understand a bit how to deal with it from the deployment point of view, but I think this does not prevent to merge this PR.

I agree, let me know if you want to further discuss it somewhere else. Considering the volume of the API surface of iDynTree, I'd not been very keen to maintain manual pybind11 bindings. In this specific case, SWIG works really well. However, if anyone wants to take the burden, I wouldn't have anything against it.

**Pull request merged**
