### PR TITLE
Regenerated all bindings after new method added 'checkDoublesAreEqual'

### PR DESCRIPTION
**Pull request by nunoguedelha**
Regenerated all bindings with the following iDynTree/Swig commits:

iDynTree commit: https://github.com/robotology/iDynTree/commit/1e261d15a4a31fe7fed7e2a836239741ecea2260
Swig commit:     https://github.com/robotology-dependencies/swig/commit/7e61db6b5dc841027439081aed3bf8c36c9e1920

### CODE REVIEW

**Comment by traversaro** [comment]
Sorry @nunoguedelha , I missed that. @prashanthr05 have you checked this?

**Comment by traversaro** [comment]
@nunoguedelha do you think it is ok to merge?

**Comment by prashanthr05** [comment]
@traversaro the bindings for ThreeAxisForceTorqueContactSensor is still missing with this commit.

**Comment by nunoguedelha** [comment]
@traversaro @prashanthr05 let me take a look. Honestly I had totally forgotten about this   x D

**Comment by nunoguedelha** [comment]
Updated the bindings interface (`.i`) files for `ThreeAxisForceTorqueContactSensor`.

@traversaro it would be nice to rename `iDynTree/Sensors/SixAxisFTSensor.h` to `iDynTree/Sensors/SixAxisForceTorqueSensor.h` to follow the same rationale as for the other sensors.

I've realized that when greping for the class `SixAxisForceTorqueSensor` for cross-checking what should be updated when adding new sensor bindings. Because of the current name we miss the grep in `iDynTree.i`.

**Comment by traversaro** [comment]
> @traversaro it would be nice to rename iDynTree/Sensors/SixAxisFTSensor.h to iDynTree/Sensors/SixAxisForceTorqueSensor.h to follow the same rationale as for the other sensors.

It makes sense, I agree.

**Comment by nunoguedelha** [comment]
Travis is failing because of a conflicting forward declaration : 
```
Scanning dependencies of target idyntree-icub-kdl
[ 67%] Building CXX object src/legacy/icub-kdl/CMakeFiles/idyntree-icub-kdl.dir/src/TorqueEstimationTree.cpp.o
In file included from /home/travis/build/robotology/idyntree/src/legacy/icub-kdl/src/TorqueEstimationTree.cpp:13:
In file included from /home/travis/build/robotology/idyntree/src/legacy/icub-kdl/include/iCub/iDynTree/idyn2kdl_icub.h:18:
/home/travis/build/robotology/idyntree/src/legacy/icub-kdl/include/iCub/iDynTree/iDyn2KDL.h:36:15: error: 
      definition of type 'Vector' conflicts with typedef of the same name
        class Vector;
              ^
/usr/local/include/yarp/sig/Vector.h:36:34: note: 'Vector' declared here
        typedef VectorOf<double> Vector;
```
This is related to https://github.com/robotology/yarp/pull/1657 which refactored the class `Vector` to be a typedef of `VectorOF<double>`.

Pushing a fix shortly...

**Comment by nunoguedelha** [comment]
@traversaro  ok. Don't worry,  was doing these tentatives as a background task anyway.

**Comment by traversaro** [comment]
Sorry @nunoguedelha ,  I forgot one request. Can you add back a `SixAxisFTSensor.h` that just includes the new SixAxisForceTorqueSensor.h with the following format:
https://github.com/robotology/idyntree/blob/3fc1206dc5b8dfa5cd6b11f195ad5b7568ef771e/src/model/include/iDynTree/Model/Indeces.h ? At the next major release of iDynTree, we can remove it.

**Pull request merged**
