### PR TITLE
Enable the compilation of pybind11 bindings in CI when conda is used

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
The first step towards #782 

This depends on #936

### CODE REVIEW

**Comment by traversaro** [comment]
Wow, you beat me by three minutes (see https://github.com/robotology/idyntree/pull/938). Can you also enable the SWIG bindings while you are at it? It should be just necessary to also install swig, and pass `-DIDYNTREE_USES_PYTHON:BOOL=ON` to the configure step.

**Comment by traversaro** [comment]
Also here the same problem of https://github.com/robotology/idyntree/issues/867 appears, probably it is a problem of modern pybind11, not related to pip.

**Comment by traversaro** [comment]
Indeed, `SYSTEM` is not a documented option of `pybind11_add_module` in latest pybind11, see https://pybind11.readthedocs.io/en/stable/compiling.html#pybind11-add-module, probably we can just remove it?

**Comment by traversaro** [comment]
Indeed, `SYSTEM` was a completly documented and legal option in pybind11 2.4.3 (the version used in Ubuntu 20.04), see https://github.com/pybind/pybind11/blob/v2.4.3/docs/compiling.rst#pybind11_add_module . Perhaps we are witnessing a rare example of *romanata* in the wild?

**Comment by traversaro** [comment]
> Perhaps we are witnessing a rare example of _romanata_ in the wild? @francesco-romano

After thinking about it during dinner, I think it is not a *romanata*. A *romanata* is the use of a not strictly necessary (but fully documented and supported) feature that leads to a bug or problem due to some corner case behaviour. In this case, the `SYSTEM` keyword was deliberatly removed upstream in pybind11, so it is not a corner case behaviour.

**Comment by traversaro** [comment]
> 
> 
> Indeed, `SYSTEM` is not a documented option of `pybind11_add_module` in latest pybind11, see https://pybind11.readthedocs.io/en/stable/compiling.html#pybind11-add-module, probably we can just remove it?

Even if it is not documented, `SYSTEM` is a parsed option (see https://github.com/pybind/pybind11/blob/v2.8.1/tools/pybind11Tools.cmake#L148) so even if we use it it should not result in that error. However, according to https://github.com/pybind/pybind11/pull/2338 : 
> CMake treats all IMPORTED targets as SYSTEM, so this was/is always on when using configuration mode. 

So in any case (even with pybind11 2.4.3) it should not be necessary to use `SYSTEM`, so we can safely remove it.

**Comment by traversaro** [comment]
A little bit of magic is still necessary for multi config generators.

**Comment by traversaro** [comment]
> A little bit of magic is still necessary for multi config generators, I can look into it.

The issue is a bit more complicated than I expected, for now I disabled the Python/pybind tests on Windows and I opened an issue https://github.com/robotology/idyntree/issues/939 to keep track of this.

**Comment by GiulioRomualdi** [comment]
Since https://github.com/robotology/idyntree/pull/936 has been merged I think we should rebase the PR on `devel`

**Comment by traversaro** [comment]
> 
> 
> Since #936 has been merged I think we should rebase the PR on `devel`

Ack, I can do that.

**Comment by traversaro** [comment]
Done!

**Review by traversaro — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
feel free to merge it :)

**Pull request merged**
