### PR TITLE
[Estimation][AttitudeEstimator] Fix bug caused by private headers included in public headers

### PR DESCRIPTION
**Pull request by prashanthr05**
Fixing private headers for issue [#519](https://github.com/robotology/idyntree/issues/519)

### CODE REVIEW

**Comment by prashanthr05** [comment]
@traversaro

**Comment by traversaro** [comment]
I guess there is something wrong in the commit history. 
Can you rebase on the latest `devel` ?

**Comment by prashanthr05** [comment]
> I guess there is something wrong in the commit history.
> Can you rebase on the latest `devel` ?

Yeah, I'm sorry. I kinda messed up pulling `upstream devel` instead of `origin devel` onto the branch. I will fix it.

**Comment by traversaro** [comment]
Nitpick: more descriptive PR titles are helpful, thanks!

**Comment by prashanthr05** [comment]
> Nitpick: more descriptive PR titles are helpful, thanks!

Noted. Thanks. I have force updated the branch to be coherent with the latest devel.

**Comment by traversaro** [comment]
Thanks!

**Pull request merged**
