### PR TITLE
Remove functionalities deprecated in iDynTree 1

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/idyntree/issues/742 .

### CODE REVIEW

**Comment by S-Dafarra** [comment]
I have tried compiling it in my machine, but it failed because of the bindings. I guess those need to be changed as well right?

**Comment by traversaro** [comment]
> 
> 
> I have tried compiling it in my machine, but it failed because of the bindings. I guess those need to be changed as well right?

Yes, sorry I was a bit to optimistic assigning reviewers before checking the CI. I still need to work to fix the CI.

**Comment by traversaro** [comment]
> 
> 
> > I have tried compiling it in my machine, but it failed because of the bindings. I guess those need to be changed as well right?
> 
> Yes, sorry I was a bit to optimistic assigning reviewers before checking the CI. I still need to work to fix the CI.

The `ExtWrenchesAndJointTorquesEstimator::loadModelAndSensorsFromFile` is still used in a lot of repos, there is no specific reason to drop it.

**Comment by traversaro** [comment]
The PR is now ready for review. @S-Dafarra @lrapetti It is quite massive and just removals and cleanup code that was using deprecate functions, so feel free to just give a glance to it.

**Review by S-Dafarra — APPROVED** [review]

**Pull request merged**
