### PR TITLE
Add MatrixView and Span in InverseKinematics

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR introduces the possibility to use MatrixView and Span as input in InverseKinematics class.

I also changed the signature of `setProjectionAlongDirection` and `projectAlongDirection` to take const references to vectors.

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Python tests fail :(

**Comment by traversaro** [comment]
> I also changed the signature of `setProjectionAlongDirection` and `projectAlongDirection` to take const references to vectors.

Can you drop this change, i.e. the commit https://github.com/robotology/idyntree/commit/5a578123147858a83585f9f28629735d44427a3b and similar changes in public APIs? It is an ABI-breaking change, and I think it would be great to land this change in iDynTree 3.x . Similar changes in private headers (such as changes in private/InverseKinematicsData.h) are ok instead. To avoid forgetting about this when we break ABI again, I added the issue https://github.com/robotology/idyntree/issues/823 .

**Comment by GiulioRomualdi** [comment]
Done! Let me know if it's ok. 

I'm implementing the test

**Review by traversaro — COMMENTED** [review]
Perfect!

**Comment by traversaro** [comment]
> I'm implementing the test

Let me know if you are working on this, otherwise we can also merge it as it is for me.

**Comment by GiulioRomualdi** [comment]
> Let me know if you are working on this, otherwise we can also merge it as it is for me.

I try to write the test before Monday.

I would be sure that everything is working as expected before merging

**Comment by traversaro** [comment]
> 
> 
> > Let me know if you are working on this, otherwise we can also merge it as it is for me.
> 
> I try to write the test before Monday.
> 
> I would be sure that everything is working as expected before merging

Ok!

**Comment by GiulioRomualdi** [comment]
Thanks to the test I wrote in https://github.com/robotology/idyntree/pull/822/commits/cecad9b37467914ba84209e12120779cd8570eec I was able to spot a bug that has been fixed in https://github.com/robotology/idyntree/pull/822/commits/cecad9b37467914ba84209e12120779cd8570eec

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Can we merge this? Squash and merge?

**Comment by GiulioRomualdi** [comment]
Yes you can squash!

**Pull request merged**
